-- =====================================================
-- V25: Audit History — Hibernate Envers
-- Bảng audit_revision_log (revision metadata)
-- + 8 bảng *_HIS (snapshot entity tại mỗi revision)
--
-- Quy tắc bảng _HIS:
--   - Sao chép toàn bộ columns của entity gốc
--   - Thêm REV BIGINT + REVTYPE SMALLINT
--   - PRIMARY KEY (id, REV)
--   - Không có FK constraints, không có unique/check constraints
--   - Index duy nhất trên REV để query theo revision
-- =====================================================

-- ─── Revision metadata ───────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS audit_revision_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp  BIGINT        NOT NULL,
    actor      VARCHAR(100),
    created_at TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_revision_timestamp ON audit_revision_log (timestamp);

-- ─── item_HIS ────────────────────────────────────────────────────────────────
-- Single-table inheritance: item_type phân biệt INGREDIENT / SEMI_PRODUCT / PRODUCT

CREATE TABLE IF NOT EXISTS item_HIS (
    -- Envers columns
    REV      BIGINT   NOT NULL REFERENCES audit_revision_log(id),
    REVTYPE  SMALLINT,          -- 0=ADD, 1=MOD, 2=DEL

    -- Entity identity
    id       UUID NOT NULL,

    -- Discriminator (item type)
    item_type VARCHAR(30),

    -- Item fields
    code          VARCHAR(50),
    name          VARCHAR(200),
    unit          VARCHAR(30),
    item_group_id UUID,
    unit_size     NUMERIC(15, 4),
    is_splittable BOOLEAN,
    unit_cost     NUMERIC(15, 4),

    -- BaseEntity audit fields
    status           VARCHAR(20),
    approval_status  VARCHAR(30),
    approved_at      TIMESTAMPTZ,
    approved_by      VARCHAR(100),
    rejected_reason  VARCHAR(500),
    created_at       TIMESTAMPTZ,
    created_by       VARCHAR(100),
    updated_at       TIMESTAMPTZ,
    updated_by       VARCHAR(100),

    PRIMARY KEY (id, REV)
);

CREATE INDEX IF NOT EXISTS idx_item_his_rev ON item_HIS (REV);

-- ─── supplier_HIS ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS supplier_HIS (
    REV     BIGINT   NOT NULL REFERENCES audit_revision_log(id),
    REVTYPE SMALLINT,
    id      UUID NOT NULL,

    code         VARCHAR(50),
    name         VARCHAR(200),
    contact_name VARCHAR(200),
    phone        VARCHAR(20),
    email        VARCHAR(100),
    address      VARCHAR(500),

    status          VARCHAR(20),
    approval_status VARCHAR(30),
    approved_at     TIMESTAMPTZ,
    approved_by     VARCHAR(100),
    rejected_reason VARCHAR(500),
    created_at      TIMESTAMPTZ,
    created_by      VARCHAR(100),
    updated_at      TIMESTAMPTZ,
    updated_by      VARCHAR(100),

    PRIMARY KEY (id, REV)
);

CREATE INDEX IF NOT EXISTS idx_supplier_his_rev ON supplier_HIS (REV);

-- ─── recipe_HIS ──────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS recipe_HIS (
    REV     BIGINT   NOT NULL REFERENCES audit_revision_log(id),
    REVTYPE SMALLINT,
    id      UUID NOT NULL,

    product_id      UUID,
    semi_product_id UUID,
    parent_recipe_id UUID,
    version         INTEGER,
    is_active       BOOLEAN,
    note            VARCHAR(500),

    status          VARCHAR(20),
    approval_status VARCHAR(30),
    approved_at     TIMESTAMPTZ,
    approved_by     VARCHAR(100),
    rejected_reason VARCHAR(500),
    created_at      TIMESTAMPTZ,
    created_by      VARCHAR(100),
    updated_at      TIMESTAMPTZ,
    updated_by      VARCHAR(100),

    PRIMARY KEY (id, REV)
);

CREATE INDEX IF NOT EXISTS idx_recipe_his_rev ON recipe_HIS (REV);

-- ─── recipe_line_HIS ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS recipe_line_HIS (
    REV     BIGINT   NOT NULL REFERENCES audit_revision_log(id),
    REVTYPE SMALLINT,
    id      UUID NOT NULL,

    recipe_id  UUID,
    item_id    UUID,
    quantity   NUMERIC(15, 4),
    unit       VARCHAR(30),
    sort_order INTEGER,

    status          VARCHAR(20),
    approval_status VARCHAR(30),
    approved_at     TIMESTAMPTZ,
    approved_by     VARCHAR(100),
    rejected_reason VARCHAR(500),
    created_at      TIMESTAMPTZ,
    created_by      VARCHAR(100),
    updated_at      TIMESTAMPTZ,
    updated_by      VARCHAR(100),

    PRIMARY KEY (id, REV)
);

CREATE INDEX IF NOT EXISTS idx_recipe_line_his_rev ON recipe_line_HIS (REV);

-- ─── inventory_request_HIS ───────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS inventory_request_HIS (
    REV     BIGINT   NOT NULL REFERENCES audit_revision_log(id),
    REVTYPE SMALLINT,
    id      UUID NOT NULL,

    code                   VARCHAR(50),
    request_type           VARCHAR(20),
    request_date           DATE,
    expected_delivery_date DATE,
    source_warehouse_id    UUID,
    target_warehouse_id    UUID,
    supplier_id            UUID,
    note                   VARCHAR(500),

    status          VARCHAR(20),
    approval_status VARCHAR(30),
    approved_at     TIMESTAMPTZ,
    approved_by     VARCHAR(100),
    rejected_reason VARCHAR(500),
    created_at      TIMESTAMPTZ,
    created_by      VARCHAR(100),
    updated_at      TIMESTAMPTZ,
    updated_by      VARCHAR(100),

    PRIMARY KEY (id, REV)
);

CREATE INDEX IF NOT EXISTS idx_inventory_request_his_rev ON inventory_request_HIS (REV);

-- ─── inventory_request_line_HIS ──────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS inventory_request_line_HIS (
    REV     BIGINT   NOT NULL REFERENCES audit_revision_log(id),
    REVTYPE SMALLINT,
    id      UUID NOT NULL,

    inventory_request_id UUID,
    item_id              UUID,
    quantity             NUMERIC(15, 4),
    unit                 VARCHAR(30),
    unit_cost            NUMERIC(15, 4),
    sort_order           INTEGER,
    note                 VARCHAR(500),

    status          VARCHAR(20),
    approval_status VARCHAR(30),
    approved_at     TIMESTAMPTZ,
    approved_by     VARCHAR(100),
    rejected_reason VARCHAR(500),
    created_at      TIMESTAMPTZ,
    created_by      VARCHAR(100),
    updated_at      TIMESTAMPTZ,
    updated_by      VARCHAR(100),

    PRIMARY KEY (id, REV)
);

CREATE INDEX IF NOT EXISTS idx_inventory_request_line_his_rev ON inventory_request_line_HIS (REV);

-- ─── production_request_HIS ──────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS production_request_HIS (
    REV     BIGINT   NOT NULL REFERENCES audit_revision_log(id),
    REVTYPE SMALLINT,
    id      UUID NOT NULL,

    code            VARCHAR(50),
    production_type VARCHAR(20),
    production_date DATE,
    note            VARCHAR(500),

    status          VARCHAR(20),
    approval_status VARCHAR(30),
    approved_at     TIMESTAMPTZ,
    approved_by     VARCHAR(100),
    rejected_reason VARCHAR(500),
    created_at      TIMESTAMPTZ,
    created_by      VARCHAR(100),
    updated_at      TIMESTAMPTZ,
    updated_by      VARCHAR(100),

    PRIMARY KEY (id, REV)
);

CREATE INDEX IF NOT EXISTS idx_production_request_his_rev ON production_request_HIS (REV);

-- ─── production_request_line_HIS ─────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS production_request_line_HIS (
    REV     BIGINT   NOT NULL REFERENCES audit_revision_log(id),
    REVTYPE SMALLINT,
    id      UUID NOT NULL,

    production_request_id UUID,
    product_id            UUID,
    recipe_id             UUID,
    planned_qty           NUMERIC(15, 4),
    qty_produced          NUMERIC(15, 4),
    line_status           VARCHAR(20),
    sort_order            INTEGER,
    note                  VARCHAR(500),

    status          VARCHAR(20),
    approval_status VARCHAR(30),
    approved_at     TIMESTAMPTZ,
    approved_by     VARCHAR(100),
    rejected_reason VARCHAR(500),
    created_at      TIMESTAMPTZ,
    created_by      VARCHAR(100),
    updated_at      TIMESTAMPTZ,
    updated_by      VARCHAR(100),

    PRIMARY KEY (id, REV)
);

CREATE INDEX IF NOT EXISTS idx_production_request_line_his_rev ON production_request_line_HIS (REV);
