-- ============================================================
-- V43__seed_support_items.sql
-- Nguyên liệu hỗ trợ: bao bì, vật tư, tươi sống, dụng cụ
-- Không tính vào cost sản phẩm — dùng theo dõi chi phí tháng
-- ON CONFLICT (code) DO UPDATE → cập nhật toàn bộ thông tin
-- ============================================================

-- ── 1. Unit mới (bổ sung ngoài V36) ──────────────────────────
INSERT INTO unit (code, name) VALUES
    ('BICH', 'Bịch'),
    ('CAN', 'Can'),
    ('CAP', 'Cặp'),
    ('CUON', 'Cuộn'),
    ('MIENG', 'Miếng'),
    ('TRAI', 'Trái'),
    ('VI', 'Vỉ'),
    ('VIEN', 'Viên')
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name;

-- ── 2. Supplier ─────────────────────────────────────────────
-- Existing từ V5: CHO, SG, VD, TT, XN, TGNL, SON
-- Thêm ON CONFLICT UPDATE để đảm bảo không thiếu
INSERT INTO supplier (code, name, status, approval_status) VALUES
    ('CHO', 'CHO', 'ACTIVE', 'APPROVED'),
    ('SG', 'SG', 'ACTIVE', 'APPROVED'),
    ('SON', 'SON', 'ACTIVE', 'APPROVED'),
    ('TGNL', 'TGNL', 'ACTIVE', 'APPROVED'),
    ('TT', 'TT', 'ACTIVE', 'APPROVED'),
    ('VD', 'VD', 'ACTIVE', 'APPROVED'),
    ('XN', 'XN', 'ACTIVE', 'APPROVED')
ON CONFLICT (code) DO UPDATE SET
    name       = EXCLUDED.name,
    updated_at = NOW();

-- ── 3. Item (item_type = INGREDIENT) ────────────────────────
-- unit_cost để NULL — giá biến động, nhập qua stock_lot mỗi lần mua
INSERT INTO item (item_type, code, name, unit, default_supplier_id, status, approval_status)
SELECT 'INGREDIENT', v.code, v.name, v.unit_code,
       (SELECT id FROM supplier WHERE code = v.supplier_code LIMIT 1),
       'ACTIVE', 'APPROVED'
FROM (VALUES
    ('ING-HOP-A93', 'hộp A93', 'CAI', 'XN'),
    ('ING-HOP-PENTO', 'hộp pento', 'CAI', 'TT'),
    ('ING-DAO-BK', 'dao gấu', 'CAI', 'VD'),
    ('ING-GIAY-LOT-KHAY', 'giấy lót khây', 'CAI', 'SG'),
    ('ING-HOP-H128', 'hộp H128', 'CAI', 'TT'),
    ('ING-HOP-H19', 'hộp H19', 'CAI', 'TT'),
    ('ING-HOP-CRAF-VUONG', 'hộp Craf vuông', 'CAI', 'TT'),
    ('ING-HOP-H03', 'hộp H03', 'CAI', 'TT'),
    ('ING-NEN-0', 'nến 0', 'CAI', 'VD'),
    ('ING-NEN-1', 'nến 1', 'CAI', 'VD'),
    ('ING-NEN-2', 'nến 2', 'CAI', 'VD'),
    ('ING-NEN-3', 'nến 3', 'CAI', 'VD'),
    ('ING-NEN-4', 'nến 4', 'CAI', 'VD'),
    ('ING-NEN-5', 'nến 5', 'CAI', 'VD'),
    ('ING-NEN-6', 'nến 6', 'CAI', 'VD'),
    ('ING-NEN-7', 'nến 7', 'CAI', 'VD'),
    ('ING-NEN-8', 'nến 8', 'CAI', 'VD'),
    ('ING-NEN-9', 'nến 9', 'CAI', 'VD'),
    ('ING-NIA', 'nĩa', 'CAI', 'SG'),
    ('ING-TUI-BANH-MI-HOA-CUC', 'túi bánh mì hoa cúc', 'CAI', 'SG'),
    ('ING-TUI-DONG-BANH-12-X-27', 'túi đóng bánh 12 x 27', 'CAI', 'SG'),
    ('ING-TUI-DONG-BANH-15-X-22', 'túi đóng bánh 15 x 22', 'CAI', 'SG'),
    ('ING-TUI-DONG-BANH-17-X-24', 'túi đóng bánh 17 x 24', 'CAI', 'SG'),
    ('ING-TUI-LAN-TAM-GIAC', 'túi lan tam giác', 'CAI', 'SG'),
    ('ING-CAFE-DEN-GOI', 'cafe đen gói', 'CAI', 'CHO'),
    ('ING-TAM-TRE', 'tăm tre', 'HOP', 'CHO'),
    ('ING-THUOC-TAY-CHA-SAN', 'thuốc tẩy chà sân', 'CHAI', 'CHO'),
    ('ING-TUI-DUNG-RAC', 'túi đựng rác', 'CAY', 'CHO'),
    ('ING-VI-CHA-NOI', 'vỉ chà nồi', 'VI', 'CHO'),
    ('ING-VIEM', 'viêm', 'CHAI', 'CHO'),
    ('ING-BAO-TAY-LEN-CAP', 'bao tay len ( cặp)', 'CAP', 'CHO'),
    ('ING-BAO-TAY-LO', 'bao tay lò', 'CAP', 'SG'),
    ('ING-BOT-XE-DAP', 'bột xe đạp', 'KG', 'VD'),
    ('ING-DUONG-BOT', 'đường bột', 'KG', 'VD'),
    ('ING-DUONG-CAT', 'đường cát', 'KG', 'CHO'),
    ('ING-HUONG-DUA', 'hương dứa', 'KG', 'VD'),
    ('ING-HUONG-SUA', 'hương sữa', 'KG', 'VD'),
    ('ING-KEM-PHO-MAI', 'kem phô mai', 'KG', 'SON'),
    ('ING-KEM-VIVO', 'kem vivo', 'KG', 'VD'),
    ('ING-MEN-LAT', 'men lạt', 'KG', 'VD'),
    ('ING-MEN-NGOT', 'men ngọt', 'KG', 'VD'),
    ('ING-MUT-CAM-NHA-DAM', 'mứt cam nha đam', 'KG', 'TGNL'),
    ('ING-NHAN-DAU-XANH', 'nhân đậu xanh', 'KG', 'VD'),
    ('ING-NHAN-MON', 'nhân môn', 'KG', 'VD'),
    ('ING-NHO', 'nho', 'KG', 'TT'),
    ('ING-PHOMAI-SOI', 'phomai sợi', 'KG', 'TGNL'),
    ('ING-PHU-GIA-LAT', 'phụ gia lạt', 'KG', 'VD'),
    ('ING-PHU-GIA-NGOT', 'phụ gia ngọt', 'KG', 'VD'),
    ('ING-SP-5KG', 'sp (5kg)', 'KG', 'VD'),
    ('ING-SU-KEM-1-KG', 'su kem 1 kg', 'KG', 'VD'),
    ('ING-GALENTINE-BOT', 'galentine bột', 'KG', 'TT'),
    ('ING-CHEN-GIAY-SO-15', 'chén giấy số 15', 'CAI', 'TT'),
    ('ING-CHEN-GIAY-SO-8', 'chén giấy số 8', 'CAI', 'TT'),
    ('ING-GIAY-LOT-PENTO', 'giấy lót pento', 'CAI', 'SG'),
    ('ING-BOT-TARTA', 'bột tarta', 'KG', NULL),
    ('ING-GODEN-FARM-CHANH-DAY', 'goden farm chanh dây', 'KG', 'XN'),
    ('ING-GODEN-FARM-KIWI', 'goden farm kiwi', 'KG', 'XN'),
    ('ING-HUONG-BAP', 'hương bắp', 'KG', 'VD'),
    ('ING-KEM-MAN', 'kem mặn', 'KG', 'SON'),
    ('ING-KEM-NIGARI-FARM', 'kem nigari farm', 'KG', 'SON'),
    ('ING-MASCAPON', 'mascapon', 'KG', 'XN'),
    ('ING-MAU-CAM-TUOI', 'màu cam tươi', 'KG', 'SG'),
    ('ING-MAU-DA-IVORY', 'màu da ivory', 'KG', 'SG'),
    ('ING-MAU-DO-CHERRY', 'màu đỏ cherry', 'KG', 'SG'),
    ('ING-MAU-HONG-DAU', 'màu hồng dâu', 'KG', 'SG'),
    ('ING-MAU-NAU-GO', 'màu nâu gỗ', 'KG', 'SG'),
    ('ING-MAU-TIM-LAVENDER', 'màu tím lavender', 'KG', 'SG'),
    ('ING-MAU-TIM-RASPERRY', 'màu tím rasperry', 'KG', 'SG'),
    ('ING-MAU-VANG-DAT', 'màu vàng đất', 'KG', 'SG'),
    ('ING-MAU-XANH-DA-TROI', 'màu xanh da trời', 'KG', 'SG'),
    ('ING-MAU-XANH-REU', 'màu xanh rêu', 'KG', 'SG'),
    ('ING-MAU-XANH-TRAI-BO', 'màu xanh trái bơ', 'KG', 'SG'),
    ('ING-MY-CREAMS', 'my creams', 'KG', 'SON'),
    ('ING-RUOU-KLUA', 'rượu klua', 'KG', 'TT'),
    ('ING-SOCOLA-NUT-DEN', 'socola nut đen', 'KG', 'XN'),
    ('ING-WHIPPING', 'whipping', 'KG', 'TGNL'),
    ('ING-YUM-CHERRY', 'yum cherry', 'KG', 'SG'),
    ('ING-YUM-DAU', 'yum dâu', 'KG', 'SG'),
    ('ING-DIA-SET-10', 'dĩa set 10', 'BO', 'SG'),
    ('ING-NEN-TANG-BANH-KEM', 'nến tặng bánh kem', 'VI', 'SG'),
    ('ING-TUI-SANDWICH', 'túi sandwich', 'CAI', 'SG'),
    ('ING-TUI-SO-2', 'túi số 2', 'CAI', 'SG'),
    ('ING-TUI-SO-3', 'túi số 3', 'CAI', 'SG'),
    ('ING-HOP-BANH-FLAN', 'hộp bánh flan', 'CAI', 'TGNL'),
    ('ING-TRUNG-MUOI', 'trứng muối', 'KG', 'TT'),
    ('ING-TUI-SO-1', 'túi số 1', 'CAI', 'SG'),
    ('ING-BERINO-DAU', 'berino dâu', 'KG', 'XN'),
    ('ING-BERINO-VIET-QUAT', 'berino việt quất', 'KG', 'TT'),
    ('ING-BO-FE', 'bơ fe', 'KG', 'VD'),
    ('ING-BOT-BAP', 'bột bắp', 'KG', 'TT'),
    ('ING-BOT-TRA-XANH', 'bột trà xanh', 'KG', 'TGNL'),
    ('ING-CHA-BONG-CAY', 'chà bông cay', 'KG', 'SG'),
    ('ING-CHA-BONG-TRANG', 'chà bông trắng', 'KG', 'SG'),
    ('ING-CHA-BONG-VANG', 'chà bông vàng', 'KG', 'SG'),
    ('ING-CHEESE', 'cheese', 'KG', 'SON'),
    ('ING-GALENTINE-LA', 'galentine lá', 'KG', 'XN'),
    ('ING-HANH-NHAN-LAT', 'hạnh nhân lát', 'KG', 'TT'),
    ('ING-HOP-PANACOTTA', 'hộp panacotta', 'CAI', 'TT'),
    ('ING-KEM-BAZE', 'kem baze', 'KG', 'SON'),
    ('ING-KEM-GOLD', 'kem gold', 'KG', 'SON'),
    ('ING-KEM-RICH-LUN', 'kem rich lùn', 'KG', 'SON'),
    ('ING-KEM-VALUE-VANG', 'kem value vàng', 'KG', 'SON'),
    ('ING-MAU-DEN', 'màu đen', 'KG', 'SG'),
    ('ING-MAU-SIEU-DO', 'màu siêu đỏ', 'KG', 'SG'),
    ('ING-MAU-VANG-TUOI', 'màu vàng tươi', 'KG', 'SG'),
    ('ING-SOCOLA-DEN', 'socola đen', 'KG', 'XN'),
    ('ING-SOCOLA-SET', 'socola sệt', 'KG', 'VD'),
    ('ING-SOCOLA-TRANG', 'socola trắng', 'KG', 'XN'),
    ('ING-SUA-TUOI', 'sữa tươi', 'HOP', 'TGNL'),
    ('ING-BOT-CACAO', 'bột cacao', 'KG', 'TT'),
    ('ING-BOT-KHOAI-LANG-TIM', 'bột khoai lang tím', 'KG', 'XN'),
    ('ING-BOT-NANG', 'bột năng', 'KG', 'TT'),
    ('ING-BOT-NOI', 'bột nổi', 'KG', 'VD'),
    ('ING-BOT-REDVELET', 'bột redvelet', 'KG', 'VD'),
    ('ING-BOT-CHIEN-XU', 'bột chiên xù', 'KG', 'CHO'),
    ('ING-BOT-DEO', 'bột dẻo', 'KG', 'TT'),
    ('ING-CHANH', 'chanh', 'KG', NULL),
    ('ING-BOT-GAO', 'bột gạo', 'KG', 'TT'),
    ('ING-BOT-KHAI', 'bột khai', 'KG', 'TT'),
    ('ING-BOT-NEP', 'bột nếp', 'KG', 'TT'),
    ('ING-DA-BAO-CHA', 'da bao chả', 'KG', 'CHO'),
    ('ING-CAROT', 'carot', 'KG', 'CHO'),
    ('ING-GAS-BO', 'gas bò', 'BINH', 'CHO'),
    ('ING-DAU-AN', 'dầu ăn', 'KG', 'CHO'),
    ('ING-DAU-ME', 'dầu mè', 'KG', 'CHO'),
    ('ING-DAU-SIMPLY', 'dầu simply', 'KG', 'CHO'),
    ('ING-DUA-BAO', 'dừa bào', 'KG', 'CHO'),
    ('ING-GAS-NHO', 'gas nhỏ', 'BINH', 'CHO'),
    ('ING-HUONG-CHUOI', 'hương chuối', 'ONG', 'CHO'),
    ('ING-HANH-LA', 'hành lá', 'KG', 'CHO'),
    ('ING-MACH-NHA', 'mạch nha', 'KG', 'TT'),
    ('ING-MAJO', 'majo', 'KG', 'CHO'),
    ('ING-MAU-DIEU', 'màu điều', 'KG', 'CHO'),
    ('ING-HANH-TAY', 'hành tây', 'KG', 'CHO'),
    ('ING-MUC', 'mực', 'KG', 'CHO'),
    ('ING-MUOI', 'muối', 'KG', 'CHO'),
    ('ING-HOP-THIEC-CHU-NHAT', 'hộp thiếc chữ nhật', 'CAI', 'TT'),
    ('ING-HOP-LAN-CHUOI', 'hộp lan chuối', 'CAI', 'SG'),
    ('ING-OT-CHUONG', 'ớt chuông', 'KG', 'CHO'),
    ('ING-NHAN-TRON', 'nhân trộn', 'KG', 'CHO'),
    ('ING-TOM', 'tôm', 'KG', 'CHO'),
    ('ING-NUOC-XA-XIU', 'nước xá xíu', 'KG', 'CHO'),
    ('ING-PATE', 'pate', 'KG', 'CHO'),
    ('ING-RONG-BIEN', 'rong biển', 'KG', 'CHO'),
    ('ING-DE-18', 'đế 18', 'CAI', 'SG'),
    ('ING-DE-22', 'đế 22', 'CAI', 'SG'),
    ('ING-DE-25', 'đế 25', 'CAI', 'SG'),
    ('ING-SAU-RIENG-KEM', 'sầu riêng kem', 'KG', NULL),
    ('ING-SORTANING-25KG', 'sortaning ( 25kg)', 'KG', 'VD'),
    ('ING-DE-28', 'đế 28', 'CAI', 'SG'),
    ('ING-DE-30', 'đế 30', 'CAI', 'SG'),
    ('ING-THIT-XA-XIU', 'thịt  xá xíu', 'KG', 'CHO'),
    ('ING-THIT-NHAN-BANH-BAO', 'thịt nhân bánh bao', 'KG', 'CHO'),
    ('ING-TUONG-CA', 'tương cà', 'KG', 'CHO'),
    ('ING-VITMIN-C', 'vitmin c', 'VIEN', 'TT'),
    ('ING-XUC-XICH', 'xúc xích', 'KG', 'CHO'),
    ('ING-XUC-XICH-CAT', 'xúc xích cắt', 'KG', 'CHO'),
    ('ING-DUONG-DONUT', 'đường donut', 'KG', 'SG'),
    ('ING-BOT-CHONG-MOC', 'bột chống móc', 'KG', 'SG'),
    ('ING-NUOC-COT-DUA', 'nước cốt dừa', 'KG', NULL),
    ('ING-BICH-KIENG-20', 'bịch kiếng 20', 'CAI', 'CHO'),
    ('ING-DE-CHONG-TANG', 'đế chồng tầng', 'CAI', 'VD'),
    ('ING-HOP-BLTM-E1685', 'hộp bltm( E1685)', 'CAI', 'SG'),
    ('ING-HOP-TIRA-TIM', 'hộp tira tim', 'CAI', 'SG'),
    ('ING-BO-HOP-BANH-18', 'bộ hộp bánh 18', 'BO', 'CHO'),
    ('ING-BO-HOP-BANH-22', 'bộ hộp bánh 22', 'BO', 'CHO'),
    ('ING-BO-HOP-BANH-26', 'bộ hộp bánh 26', 'BO', 'CHO'),
    ('ING-BO-HOP-BANH-3-TANG', 'bộ hộp bánh 3 tầng', 'BO', 'CHO'),
    ('ING-BO-HOP-BANH-34', 'bộ hộp bánh 34', 'BO', 'CHO'),
    ('ING-VANI', 'vani', 'ONG', 'CHO'),
    ('ING-TRUNG-DANH-BOT', 'trứng đánh bột', 'KG', 'CHO'),
    ('ING-HOP-H15-BAU', 'hộp H15 bầu', 'CAI', 'TT'),
    ('ING-HOP-TIRA-VUONG', 'hộp tira vuông', 'CAI', 'SG'),
    ('ING-LY-MIX-VI-5550', 'ly mix vị(5550)', 'CAI', 'SG'),
    ('ING-TAM-CHONG-TANG', 'tăm chống tầng', 'CAI', 'VD'),
    ('ING-TRA-OLONG', 'trà olong', 'KG', 'TT'),
    ('ING-DE-32', 'đế 32', 'CAI', 'SG'),
    ('ING-DE-35', 'đế 35', 'CAI', 'SG'),
    ('ING-DE-40', 'đế 40', 'CAI', 'SG'),
    ('ING-HOP-1-BANH', 'hộp 1 bánh', 'CAI', 'SG'),
    ('ING-HOP-18X18', 'hộp 18x18', 'CAI', 'SG'),
    ('ING-HOP-2-BANH', 'hộp 2 bánh', 'CAI', 'SG'),
    ('ING-HOP-22X20', 'hộp 22x20', 'CAI', 'SG'),
    ('ING-HOP-25X20', 'hộp 25x20', 'CAI', 'SG'),
    ('ING-HOP-28X20', 'hộp 28x20', 'CAI', 'SG'),
    ('ING-MUT-BAP', 'mứt bắp', 'KG', 'CHO'),
    ('ING-NUOC-CHANH-DAY', 'nước chanh dây', 'KG', 'CHO'),
    ('ING-BICH-BANH-MI-DAI', 'bịch bánh mì dài', 'CAI', 'CHO'),
    ('ING-BICH-DEP-20', 'bịch đẹp 20', 'CAI', 'CHO'),
    ('ING-BICH-DEP-24', 'bịch đẹp 24', 'CAI', 'CHO'),
    ('ING-BICH-DEP-26', 'bịch đẹp 26', 'CAI', 'CHO'),
    ('ING-BICH-KIENG-15-SW', 'bịch kiếng 15 (sw)', 'CAI', 'CHO'),
    ('ING-BICH-XOP-50', 'bịch xốp 50', 'CAI', 'CHO'),
    ('ING-BICH-XOP-60', 'bịch xốp 60', 'CAI', 'CHO'),
    ('ING-HOP-3-BANH', 'hộp 3 bánh', 'CAI', 'SG'),
    ('ING-HOP-30X20', 'hộp 30x20', 'CAI', 'SG'),
    ('ING-HOP-30X25', 'hộp 30x25', 'CAI', 'SG'),
    ('ING-HOP-30X30', 'hộp 30x30', 'CAI', 'SG'),
    ('ING-HOP-32X20', 'hộp 32x20', 'CAI', 'SG'),
    ('ING-HOP-35X20', 'hộp 35x20', 'CAI', 'SG'),
    ('ING-HOP-35X25', 'hộp 35x25', 'CAI', 'SG'),
    ('ING-HOP-40X20', 'hộp 40x20', 'CAI', 'SG'),
    ('ING-HOP-BANH-BAO', 'hộp bánh bao', 'CAI', 'CHO'),
    ('ING-HOP-H24', 'hộp H24', 'CAI', 'VD'),
    ('ING-HOP-P500D', 'hộp P500D', 'CAI', 'CHO'),
    ('ING-HOP-HT203', 'hộp HT203', 'CAI', 'TT'),
    ('ING-TUI-SET-QUA', 'túi set quà', 'CAI', 'SG'),
    ('ING-TUONG-CA-NHO', 'tương cà nhỏ', 'CAI', 'CHO'),
    ('ING-HOP-CRAF-CHU-NHAT', 'hộp Craf chữ nhật', 'CAI', 'TT'),
    ('ING-HOP-TAM-GIAC', 'hộp tam giác', 'CAI', 'VD'),
    ('ING-TUI-VAI-0018', 'túi vải 0018', 'CAI', 'SG'),
    ('ING-TUI-VAI-2225', 'túi vải 2225', 'CAI', 'SG'),
    ('ING-TUI-VAI-2830', 'túi vải 2830', 'CAI', 'SG'),
    ('ING-NUOC-XIT-TAY-LO', 'nước xịt tẩy lò', 'CHAI', 'CHO'),
    ('ING-TUONG-OT-NHO', 'tương ớt nhỏ', 'CAI', 'CHO'),
    ('ING-HOP-TIRA-SIZE-10', 'hộp tira size 10', 'CAI', 'SG'),
    ('ING-BICH-XOP-10', 'bịch xốp 10', 'KG', 'CHO'),
    ('ING-TUI-DAN-10', 'túi dán 10', 'KG', 'CHO'),
    ('ING-HOP-PET-500', 'hộp pet 500', 'CAI', 'XN'),
    ('ING-HOP-PET-750', 'hộp pet 750', 'CAI', 'XN'),
    ('ING-MUONG-NHO', 'muỗng nhỏ', 'CAI', 'TGNL'),
    ('ING-BANH-OREO', 'bánh oreo', 'CAY', 'CHO'),
    ('ING-BOT-PHO-MAI', 'bột phô mai', 'KG', 'TT'),
    ('ING-BOT-SUA', 'bột sữa', 'KG', 'TGNL'),
    ('ING-BANG-KEO-LON', 'băng keo lớn', 'CAI', 'CHO'),
    ('ING-BANG-KEO-MINI', 'băng keo mini', 'CAI', 'CHO'),
    ('ING-PHO-MAI-LAT', 'pho mai lát', 'KG', 'CHO'),
    ('ING-PHOMAI-BO-CUOI', 'phomai bò cười', 'MIENG', 'CHO'),
    ('ING-BANG-KEO-MY-LY', 'băng keo mỹ lý', 'CAI', 'SG'),
    ('ING-BANG-KEO-SW', 'băng keo sw', 'CAI', 'CHO'),
    ('ING-SUA-CHUA-KHONG-DUONG', 'sữa chua không đường', 'HOP', 'CHO'),
    ('ING-SUA-DAC', 'sữa đặc', 'KG', 'CHO'),
    ('ING-TRUNG-CUT', 'trứng cút', 'QUA', NULL),
    ('ING-THOM-SEN', 'thơm sên', 'KG', 'CHO'),
    ('ING-TRUNG-VIT', 'trứng vịt', 'QUA', NULL),
    ('ING-BAP-MY', 'bắp mỹ', 'TRAI', NULL),
    ('ING-CA-ROT', 'cà rốt', 'KG', NULL),
    ('ING-CHA', 'chả', 'KG', NULL),
    ('ING-CHANH-DAY-TRAI', 'chanh dây trái', 'KG', NULL),
    ('ING-CHUOI', 'chuối', 'KG', NULL),
    ('ING-CU-SAN', 'củ sắn', 'KG', NULL),
    ('ING-DA-BAO', 'da bao', 'KG', NULL),
    ('ING-DAU-HA-LAN', 'đậu hà lan', 'KG', NULL),
    ('ING-DAU-PHONG', 'đậu phộng', 'KG', NULL),
    ('ING-HANH-PHI', 'hành phi', 'KG', NULL),
    ('ING-HANH-TIM', 'hành tím', 'KG', NULL),
    ('ING-KHOAI-LANG', 'khoai lang', 'KG', NULL),
    ('ING-LA-DUA', 'lá dứa', 'KG', NULL),
    ('ING-LAP-XUONG', 'lạp xưởng', 'KG', NULL),
    ('ING-ME-DEN', 'mè đen', 'KG', NULL),
    ('ING-ME-TRANG', 'mè trắng', 'KG', NULL),
    ('ING-MO-HEO', 'mỡ heo', 'KG', NULL),
    ('ING-MUC-2', 'mực', 'KG', NULL),
    ('ING-MUT-BI', 'mứt bí', 'KG', NULL),
    ('ING-NAM-MEO', 'nấm mèo', 'KG', NULL),
    ('ING-NGO-RI', 'ngò rí', 'KG', NULL),
    ('ING-OT-CHUONG-2', 'ớt chuông', 'KG', NULL),
    ('ING-SA', 'sả', 'KG', NULL),
    ('ING-TAT', 'tắt', 'KG', NULL),
    ('ING-THANH-CUA', 'thanh cua', 'KG', NULL),
    ('ING-THIT-XAY', 'thịt xay', 'KG', NULL),
    ('ING-THOM-TRAI', 'thơm trái', 'TRAI', NULL),
    ('ING-TOI', 'tỏi', 'KG', NULL),
    ('ING-TOM-2', 'tôm', 'KG', NULL),
    ('ING-XI-MUOI', 'xí muội', 'KG', NULL),
    ('ING-HANH-TAY-2', 'hành tây', 'KG', NULL),
    ('ING-HANH-LA-2', 'hành lá', 'KG', 'CHO'),
    ('ING-BOT-BIEN-TINH', 'bột biến tính', 'KG', 'TT'),
    ('ING-BO-ANCHOR', 'bơ anchor', 'KG', 'TGNL'),
    ('ING-BO-NAUY', 'bơ nauy', 'KG', 'VD'),
    ('ING-BO-THE', 'bơ thẻ', 'KG', 'TT'),
    ('ING-BO-THOM', 'bơ thơm', 'KG', 'VD'),
    ('ING-BO-TUONG-AN', 'bơ tường an', 'KG', 'VD'),
    ('ING-BOT-555', 'bột 555', 'KG', 'VD'),
    ('ING-BOT-BEO', 'bột béo', 'KG', 'TT'),
    ('ING-BOT-BH-25KG', 'bột bh 25kg', 'KG', 'TT'),
    ('ING-BOT-BH-XANH', 'bột bh xanh', 'KG', 'TT'),
    ('ING-BOT-BUTTER-MILK', 'bột butter milk', 'KG', 'VD'),
    ('ING-BAO-TAM-GIAC', 'bao tam giác', 'KG', 'VD'),
    ('ING-CAY-DANH-BOT', 'cây đánh bột', 'CAI', 'CHO'),
    ('ING-CAY-LAU-SAN', 'cây lau sàn', 'CAI', 'CHO'),
    ('ING-BICH-PD-TU-BANH-BAO', 'bịch pd (tủ bánh bao)', 'KG', 'CHO'),
    ('ING-BOT-GIAT', 'bột giặt', 'KG', 'CHO'),
    ('ING-GIAY-LAN', 'giấy lan', 'CAI', 'CHO'),
    ('ING-NUOC-LAU-SAN', 'nước lau sàn', 'CHAI', 'CHO'),
    ('ING-NUOC-RUA-CHEN', 'nước rửa chén', 'CAN', 'CHO'),
    ('ING-THUN', 'thun', 'BICH', 'CHO'),
    ('ING-TUI-ZIP-0-5KG', 'túi zip 0.5kg', 'KG', 'CHO'),
    ('ING-TUI-ZIP-1KG', 'túi zip 1kg', 'KG', 'CHO'),
    ('ING-BAO-TAY-Y-TE', 'bao tay y tế', 'CAP', 'CHO'),
    ('ING-XIEN-QUE', 'xiên que', 'KG', 'CHO'),
    ('ING-XIEN-QUE-DONUT', 'xiên que donut', 'CAI', 'SG'),
    ('ING-GIAY-BAO', 'giấy báo', 'KG', 'CHO'),
    ('ING-KHAN-GIAY', 'khăn giấy', 'CAY', 'CHO'),
    ('ING-GIAY-SILICON', 'giấy silicon', 'CAI', 'SG'),
    ('ING-BICH-BAT-SUKEM', 'bịch bắt sukem', 'CAI', 'SG'),
    ('ING-DAU-BAT-SUKEM', 'đầu bắt sukem', 'CAI', 'SG'),
    ('ING-CAY-VET-BOT', 'cây vét bột', 'CAI', 'CHO'),
    ('ING-CHOI', 'chổi', 'CAI', 'CHO'),
    ('ING-CO-QUET', 'cọ quét', 'CAI', 'CHO'),
    ('ING-DAY-COT-BANH', 'dây cột bánh', 'CUON', 'CHO'),
    ('ING-DUNG-CU-HOT-RAC', 'dụng cụ hốt rác', 'CAI', 'CHO'),
    ('ING-GHIM-BAM', 'ghim bấm', 'HOP', 'CHO'),
    ('ING-MIENG-LAU-SAN', 'miếng lau sàn', 'CAI', 'CHO'),
    ('ING-NUOC-LAU-KINH', 'nước lau kính', 'CHAI', 'CHO'),
    ('ING-PIN-TIEU', 'pin tiểu', 'CAI', 'CHO'),
    ('ING-MANG-BOC-THUC-PHAM', 'màng bọc thực phẩm', 'CAY', 'CHO'),
    ('ING-TUI-VAI-18', 'túi vải 18', 'CAI', 'SG'),
    ('ING-TUI-VAI-22', 'túi vải 22', 'CAI', 'SG'),
    ('ING-TUI-VAI-25', 'túi vải 25', 'CAI', 'SG'),
    ('ING-TUI-VAI-2830-MOI', 'túi vải 2830', 'CAI', 'SG'),
    ('ING-TUI-VAI-3235', 'túi vải 3235', 'CAI', 'SG')
) AS v(code, name, unit_code, supplier_code)
ON CONFLICT (code) DO UPDATE SET
    name                = EXCLUDED.name,
    unit                = EXCLUDED.unit,
    default_supplier_id = EXCLUDED.default_supplier_id,
    updated_at          = NOW();

-- ── 4. Item Packaging ────────────────────────────────────────
-- qty_per_pack = số canonical unit per pack
-- ING-TRUNG-DANH-BOT: pkg Quả qty=0.05 (1 Quả = 0.05 KG)
INSERT INTO item_packaging (item_id, code, name, qty_per_pack, is_default)
SELECT i.id, v.pkg_code, v.pkg_name, v.qty::numeric, true
FROM (VALUES
    ('ING-HOP-A93', 'CAY', 'CÂY', 100.0),
    ('ING-HOP-PENTO', 'CAY', 'CÂY', 50.0),
    ('ING-DAO-BK', 'BICH', '1 BỊCH', 100.0),
    ('ING-GIAY-LOT-KHAY', 'TO', 'TỜ', 1.0),
    ('ING-HOP-H128', 'CAY', 'CÂY', 100.0),
    ('ING-HOP-H19', 'CAY', 'CÂY', 50.0),
    ('ING-HOP-CRAF-VUONG', 'CAY', 'CÂY', 50.0),
    ('ING-HOP-H03', 'CAY', 'CÂY', 100.0),
    ('ING-NEN-0', 'HOP', 'HỘP', 20.0),
    ('ING-NEN-1', 'HOP', 'HỘP', 20.0),
    ('ING-NEN-2', 'HOP', 'HỘP', 20.0),
    ('ING-NEN-3', 'HOP', 'HỘP', 20.0),
    ('ING-NEN-4', 'HOP', 'HỘP', 20.0),
    ('ING-NEN-5', 'HOP', 'HỘP', 20.0),
    ('ING-NEN-6', 'HOP', 'HỘP', 20.0),
    ('ING-NEN-7', 'HOP', 'HỘP', 20.0),
    ('ING-NEN-8', 'HOP', 'HỘP', 20.0),
    ('ING-NEN-9', 'HOP', 'HỘP', 20.0),
    ('ING-NIA', 'BICH', 'BỊCH', 100.0),
    ('ING-TUI-BANH-MI-HOA-CUC', 'KG', 'KG', 150.0),
    ('ING-TUI-DONG-BANH-12-X-27', 'KG', 'KG', 570.0),
    ('ING-TUI-DONG-BANH-15-X-22', 'KG', 'KG', 330.0),
    ('ING-TUI-DONG-BANH-17-X-24', 'KG', 'KG', 400.0),
    ('ING-TUI-LAN-TAM-GIAC', 'KG', 'KG', 500.0),
    ('ING-CAFE-DEN-GOI', 'BICH', 'BỊCH', 38.0),
    ('ING-BAO-TAY-LEN-CAP', 'BICH', 'BỊCH', 10.0),
    ('ING-BAO-TAY-LO', 'BICH', 'BỊCH', 1.0),
    ('ING-BOT-XE-DAP', 'BAO', 'BAO', 40.0),
    ('ING-DUONG-BOT', 'BICH', 'BỊCH', 1.0),
    ('ING-DUONG-CAT', 'BAO', 'BAO', 50.0),
    ('ING-HUONG-DUA', 'CHAI', 'CHAI', 1.0),
    ('ING-HUONG-SUA', 'CAN', 'CAN', 5.0),
    ('ING-KEM-PHO-MAI', 'HOP', 'HỘP', 1.0),
    ('ING-KEM-VIVO', 'HOP', 'HỘP', 1.0),
    ('ING-MEN-LAT', 'BAO', 'BAO', 0.5),
    ('ING-MEN-NGOT', 'BAO', 'BAO', 0.5),
    ('ING-MUT-CAM-NHA-DAM', 'CHAI', 'CHAI', 1.0),
    ('ING-NHAN-DAU-XANH', 'BICH', 'BỊCH', 3.0),
    ('ING-NHAN-MON', 'BICH', 'BỊCH', 3.0),
    ('ING-NHO', 'THUNG', 'THÙNG', 10.0),
    ('ING-PHOMAI-SOI', 'BICH', 'BỊCH', 1.0),
    ('ING-PHU-GIA-LAT', 'BAO', 'BAO', 0.5),
    ('ING-PHU-GIA-NGOT', 'BAO', 'BAO', 1.0),
    ('ING-SP-5KG', 'THUNG', 'THÙNG', 5.0),
    ('ING-SU-KEM-1-KG', 'BICH', '1 BỊCH', 1.0),
    ('ING-GALENTINE-BOT', 'BICH', 'BỊCH', 1.0),
    ('ING-CHEN-GIAY-SO-15', 'CAY', 'CÂY', 500.0),
    ('ING-CHEN-GIAY-SO-8', 'CAY', 'CÂY', 500.0),
    ('ING-GIAY-LOT-PENTO', 'BICH', 'BỊCH', 100.0),
    ('ING-BOT-TARTA', 'HOP', 'HỘP', 1.35),
    ('ING-GODEN-FARM-CHANH-DAY', 'CHAI', 'CHAI', 1.0),
    ('ING-GODEN-FARM-KIWI', 'CHAI', 'CHAI', 1.0),
    ('ING-HUONG-BAP', 'CHAI', 'CHAI', 0.1),
    ('ING-KEM-MAN', 'HOP', 'HỘP', 1.0),
    ('ING-KEM-NIGARI-FARM', 'HOP', 'HỘP', 1.0),
    ('ING-MASCAPON', 'BICH', 'BỊCH', 1.0),
    ('ING-MAU-CAM-TUOI', 'CHAI', 'CHAI', 0.21),
    ('ING-MAU-DA-IVORY', 'CHAI', 'CHAI', 0.21),
    ('ING-MAU-DO-CHERRY', 'CHAI', 'CHAI', 0.21),
    ('ING-MAU-HONG-DAU', 'CHAI', 'CHAI', 0.21),
    ('ING-MAU-NAU-GO', 'CHAI', 'CHAI', 0.21),
    ('ING-MAU-TIM-LAVENDER', 'CHAI', 'CHAI', 0.21),
    ('ING-MAU-TIM-RASPERRY', 'CHAI', 'CHAI', 0.21),
    ('ING-MAU-VANG-DAT', 'CHAI', 'CHAI', 0.21),
    ('ING-MAU-XANH-DA-TROI', 'CHAI', 'CHAI', 0.21),
    ('ING-MAU-XANH-REU', 'CHAI', 'CHAI', 0.21),
    ('ING-MAU-XANH-TRAI-BO', 'CHAI', 'CHAI', 0.21),
    ('ING-MY-CREAMS', 'HOP', 'HỘP', 1.0),
    ('ING-RUOU-KLUA', 'CHAI', 'CHAI', 0.7),
    ('ING-SOCOLA-NUT-DEN', 'BICH', 'BỊCH', 1.0),
    ('ING-WHIPPING', 'BICH', 'BỊCH', 1.0),
    ('ING-YUM-CHERRY', 'CHAI', 'CHAI', 0.2),
    ('ING-YUM-DAU', 'CHAI', 'CHAI', 0.2),
    ('ING-DIA-SET-10', 'BICH', 'BỊCH', 50.0),
    ('ING-NEN-TANG-BANH-KEM', 'HOP', 'HỘP', 100.0),
    ('ING-TUI-SANDWICH', 'KG', 'KG', 1.0),
    ('ING-TUI-SO-2', 'KG', 'KG', 1.0),
    ('ING-TUI-SO-3', 'KG', 'KG', 1.0),
    ('ING-HOP-BANH-FLAN', 'BICH', 'BỊCH', 50.0),
    ('ING-TRUNG-MUOI', 'BICH', 'BỊCH', 0.7),
    ('ING-TUI-SO-1', 'KG', 'KG', 1.0),
    ('ING-BERINO-DAU', 'CHAI', 'CHAI', 1.0),
    ('ING-BERINO-VIET-QUAT', 'CHAI', 'CHAI', 1.0),
    ('ING-BO-FE', 'BICH', 'BỊCH', 5.0),
    ('ING-BOT-BAP', 'BICH', 'BỊCH', 1.0),
    ('ING-BOT-TRA-XANH', 'BICH', 'BỊCH', 0.5),
    ('ING-CHA-BONG-CAY', 'BICH', 'BỊCH', 1.0),
    ('ING-CHA-BONG-TRANG', 'BICH', 'BỊCH', 1.0),
    ('ING-CHA-BONG-VANG', 'BICH', 'BỊCH', 1.0),
    ('ING-CHEESE', 'CAY', 'CÂY', 1.36),
    ('ING-GALENTINE-LA', 'HOP', 'HỘP', 1.0),
    ('ING-HANH-NHAN-LAT', 'BICH', 'BỊCH', 1.0),
    ('ING-HOP-PANACOTTA', 'BICH', 'BỊCH', 50.0),
    ('ING-KEM-BAZE', 'HOP', 'HỘP', 1.0),
    ('ING-KEM-GOLD', 'HOP', 'HỘP', 1.0),
    ('ING-KEM-RICH-LUN', 'HOP', 'HỘP', 0.454),
    ('ING-KEM-VALUE-VANG', 'HOP', 'HỘP', 1.0),
    ('ING-MAU-DEN', 'CHAI', 'CHAI', 0.21),
    ('ING-MAU-SIEU-DO', 'CHAI', 'CHAI', 0.21),
    ('ING-MAU-VANG-TUOI', 'CHAI', 'CHAI', 0.21),
    ('ING-SOCOLA-DEN', 'BICH', 'BỊCH', 1.0),
    ('ING-SOCOLA-SET', 'THUNG', 'THÙNG', 4.0),
    ('ING-SOCOLA-TRANG', 'BICH', 'BỊCH', 1.0),
    ('ING-SUA-TUOI', 'THUNG', 'THÙNG', 12.0),
    ('ING-BOT-CACAO', 'BICH', 'BỊCH', 0.5),
    ('ING-BOT-KHOAI-LANG-TIM', 'BICH', 'BỊCH', 0.05),
    ('ING-BOT-NANG', 'BICH', 'BỊCH', 1.0),
    ('ING-BOT-NOI', 'BICH', 'BỊCH', 1.0),
    ('ING-BOT-REDVELET', 'BICH', 'BỊCH', 1.0),
    ('ING-BOT-CHIEN-XU', 'BICH', 'BỊCH', 1.0),
    ('ING-BOT-DEO', 'BICH', 'BỊCH', 1.0),
    ('ING-BOT-GAO', 'BICH', 'BỊCH', 1.0),
    ('ING-BOT-KHAI', 'BICH', 'BỊCH', 1.0),
    ('ING-BOT-NEP', 'BICH', 'BỊCH', 1.0),
    ('ING-DA-BAO-CHA', 'CAY', 'CÂY', 1.0),
    ('ING-DAU-AN', 'BINH', 'BÌNH', 20.0),
    ('ING-DAU-ME', 'CHAI', 'CHAI', 0.25),
    ('ING-DAU-SIMPLY', 'CHAI', 'CHAI', 1.0),
    ('ING-HUONG-CHUOI', 'HOP', 'HỘP', 10.0),
    ('ING-MACH-NHA', 'HOP', 'HỘP', 1.0),
    ('ING-MAJO', 'HOP', 'HỘP', 1.0),
    ('ING-MAU-DIEU', 'CHAI', 'CHAI', 0.1),
    ('ING-MUOI', 'BICH', 'BỊCH', 1.0),
    ('ING-HOP-THIEC-CHU-NHAT', 'CAY', 'CÂY', 100.0),
    ('ING-HOP-LAN-CHUOI', 'CAY', 'CÂY', 50.0),
    ('ING-NHAN-TRON', 'BICH', 'BỊCH', 0.35),
    ('ING-NUOC-XA-XIU', 'BICH', 'BỊCH', 0.35),
    ('ING-PATE', 'HOP', 'HỘP', 0.7),
    ('ING-RONG-BIEN', 'BICH', 'BỊCH', 0.04),
    ('ING-SORTANING-25KG', 'THUNG', 'THÙNG', 25.0),
    ('ING-THIT-XA-XIU', 'BICH', 'BỊCH', 0.6),
    ('ING-TUONG-CA', 'CHAI', 'CHAI', 0.7),
    ('ING-XUC-XICH', 'BICH', 'BỊCH', 0.5),
    ('ING-XUC-XICH-CAT', 'BICH', 'BỊCH', 0.5),
    ('ING-BOT-CHONG-MOC', 'BICH', 'BỊCH', 1.0),
    ('ING-BICH-KIENG-20', 'KG', 'KG', 486.0),
    ('ING-DE-CHONG-TANG', 'BICH', 'BỊCH', 100.0),
    ('ING-VANI', 'HOP', 'HỘP', 100.0),
    ('ING-TRUNG-DANH-BOT', 'QUA', 'Quả', 0.05),
    ('ING-HOP-H15-BAU', 'CAY', 'CÂY', 100.0),
    ('ING-TAM-CHONG-TANG', 'BICH', 'BỊCH', 100.0),
    ('ING-TRA-OLONG', 'BICH', 'BỊCH', 1.0),
    ('ING-MUT-BAP', 'BICH', 'BỊCH', 0.85),
    ('ING-NUOC-CHANH-DAY', 'BICH', 'BỊCH', 0.5),
    ('ING-BICH-BANH-MI-DAI', 'KG', 'KG', 120.0),
    ('ING-BICH-DEP-20', 'KG', 'KG', 140.0),
    ('ING-BICH-DEP-24', 'KG', 'KG', 60.0),
    ('ING-BICH-DEP-26', 'KG', 'KG', 55.0),
    ('ING-BICH-KIENG-15-SW', 'KG', 'KG', 368.0),
    ('ING-BICH-XOP-50', 'KG', 'KG', 17.0),
    ('ING-BICH-XOP-60', 'KG', 'KG', 12.0),
    ('ING-HOP-BANH-BAO', 'CAY', 'CÂY', 50.0),
    ('ING-HOP-H24', 'CAY', 'CÂY', 50.0),
    ('ING-HOP-P500D', 'CAY', 'CÂY', 50.0),
    ('ING-HOP-HT203', 'CAY', 'CÂY', 50.0),
    ('ING-TUI-SET-QUA', 'BICH', 'BỊCH', 1.0),
    ('ING-TUONG-CA-NHO', 'BICH', 'BỊCH', 100.0),
    ('ING-HOP-CRAF-CHU-NHAT', 'CAY', 'CÂY', 50.0),
    ('ING-HOP-TAM-GIAC', 'CAY', 'CÂY', 50.0),
    ('ING-TUI-VAI-0018', 'KG', 'KG', 1.0),
    ('ING-TUI-VAI-2225', 'KG', 'KG', 1.0),
    ('ING-TUI-VAI-2830', 'KG', 'KG', 1.0),
    ('ING-TUONG-OT-NHO', 'BICH', 'BỊCH', 100.0),
    ('ING-BICH-XOP-10', 'KG', 'KG', 56.0),
    ('ING-TUI-DAN-10', 'KG', 'KG', 987.0),
    ('ING-HOP-PET-500', 'CAY', 'CÂY', 10.0),
    ('ING-HOP-PET-750', 'CAY', 'CÂY', 10.0),
    ('ING-MUONG-NHO', 'BICH', 'BỊCH', 1000.0),
    ('ING-BOT-PHO-MAI', 'BICH', 'BỊCH', 1.0),
    ('ING-BOT-SUA', 'BICH', 'BỊCH', 1.0),
    ('ING-BANG-KEO-LON', 'CAY', 'CÂY', 8.0),
    ('ING-BANG-KEO-MINI', 'CAY', 'CÂY', 10.0),
    ('ING-PHO-MAI-LAT', 'BICH', 'BỊCH', 0.2),
    ('ING-PHOMAI-BO-CUOI', 'HOP', 'HỘP', 16.0),
    ('ING-BANG-KEO-SW', 'CAY', 'CÂY', 12.0),
    ('ING-SUA-CHUA-KHONG-DUONG', 'LOC', 'LỐC', 4.0),
    ('ING-SUA-DAC', 'HOP', 'HỘP', 1.0),
    ('ING-THOM-SEN', 'HOP', 'HỘP', 4.0),
    ('ING-CHA', 'CAY', 'CÂY', 0.5),
    ('ING-DA-BAO', 'CAY', 'CÂY', 1.0),
    ('ING-DAU-HA-LAN', 'BICH', 'BỊCH', 0.5),
    ('ING-BOT-BIEN-TINH', 'BICH', 'BỊCH', 1.0),
    ('ING-BO-ANCHOR', 'BICH', 'BỊCH', 5.0),
    ('ING-BO-NAUY', 'THUNG', 'THÙNG', 4.0),
    ('ING-BO-THE', 'THUNG', 'THÙNG', 10.0),
    ('ING-BO-THOM', 'THUNG', 'THÙNG', 17.0),
    ('ING-BO-TUONG-AN', 'THUNG', 'THÙNG', 20.0),
    ('ING-BOT-555', 'BAO', 'BAO', 25.0),
    ('ING-BOT-BEO', 'BICH', 'BỊCH', 1.0),
    ('ING-BOT-BH-25KG', 'BAO', 'BAO', 25.0),
    ('ING-BOT-BH-XANH', 'BICH', 'BỊCH', 1.0),
    ('ING-BOT-BUTTER-MILK', 'HOP', 'HỘP', 1.0),
    ('ING-BAO-TAM-GIAC', 'BICH', 'BỊCH', 1.0),
    ('ING-GIAY-LAN', 'GRAM', 'GRAM', 1.0),
    ('ING-BAO-TAY-Y-TE', 'HOP', 'HỘP', 50.0),
    ('ING-XIEN-QUE', 'BICH', 'BỊCH', 0.5),
    ('ING-XIEN-QUE-DONUT', 'BICH', 'BỊCH', 100.0)
) AS v(item_code, pkg_code, pkg_name, qty)
JOIN item i ON i.code = v.item_code
ON CONFLICT (item_id, code) DO UPDATE SET
    name         = EXCLUDED.name,
    qty_per_pack = EXCLUDED.qty_per_pack,
    updated_at   = NOW();

-- ── 5. item.unit_cost — giá/đvt canonical hiện tại ─────────────
-- Chỉ update những item có giá trong Excel (26 item không có giá giữ NULL)
UPDATE item SET unit_cost = v.unit_cost, updated_at = NOW()
FROM (VALUES
    ('ING-HOP-A93', 1100.0),
    ('ING-HOP-PENTO', 1700.0),
    ('ING-DAO-BK', 700.0),
    ('ING-GIAY-LOT-KHAY', 473.0),
    ('ING-HOP-H128', 650.0),
    ('ING-HOP-H19', 1200.0),
    ('ING-HOP-CRAF-VUONG', 1700.0),
    ('ING-HOP-H03', 800.0),
    ('ING-NEN-0', 800.0),
    ('ING-NEN-1', 800.0),
    ('ING-NEN-2', 800.0),
    ('ING-NEN-3', 800.0),
    ('ING-NEN-4', 800.0),
    ('ING-NEN-5', 800.0),
    ('ING-NEN-6', 800.0),
    ('ING-NEN-7', 800.0),
    ('ING-NEN-8', 800.0),
    ('ING-NEN-9', 800.0),
    ('ING-NIA', 120.0),
    ('ING-TUI-BANH-MI-HOA-CUC', 866.67),
    ('ING-TUI-DONG-BANH-12-X-27', 0.63),
    ('ING-TUI-DONG-BANH-15-X-22', 500.0),
    ('ING-TUI-DONG-BANH-17-X-24', 412.5),
    ('ING-TUI-LAN-TAM-GIAC', 334.0),
    ('ING-CAFE-DEN-GOI', 4210.53),
    ('ING-TAM-TRE', 10000.0),
    ('ING-THUOC-TAY-CHA-SAN', 60000.0),
    ('ING-TUI-DUNG-RAC', 30000.0),
    ('ING-VI-CHA-NOI', 55000.0),
    ('ING-VIEM', 60000.0),
    ('ING-BAO-TAY-LEN-CAP', 5000.0),
    ('ING-BAO-TAY-LO', 165000.0),
    ('ING-BOT-XE-DAP', 15550.0),
    ('ING-DUONG-BOT', 45000.0),
    ('ING-DUONG-CAT', 19200.0),
    ('ING-HUONG-DUA', 125000.0),
    ('ING-HUONG-SUA', 40000.0),
    ('ING-KEM-PHO-MAI', 113000.0),
    ('ING-KEM-VIVO', 79000.0),
    ('ING-MEN-LAT', 116000.0),
    ('ING-MEN-NGOT', 116000.0),
    ('ING-MUT-CAM-NHA-DAM', 92000.0),
    ('ING-NHAN-DAU-XANH', 79000.0),
    ('ING-NHAN-MON', 80000.0),
    ('ING-NHO', 102000.0),
    ('ING-PHOMAI-SOI', 173000.0),
    ('ING-PHU-GIA-LAT', 160000.0),
    ('ING-PHU-GIA-NGOT', 98000.0),
    ('ING-SP-5KG', 74000.0),
    ('ING-SU-KEM-1-KG', 119000.0),
    ('ING-GALENTINE-BOT', 300000.0),
    ('ING-CHEN-GIAY-SO-15', 124.0),
    ('ING-CHEN-GIAY-SO-8', 100.0),
    ('ING-GIAY-LOT-PENTO', 300.0),
    ('ING-BOT-TARTA', 192592.59),
    ('ING-GODEN-FARM-CHANH-DAY', 106000.0),
    ('ING-GODEN-FARM-KIWI', 100000.0),
    ('ING-HUONG-BAP', 310000.0),
    ('ING-KEM-MAN', 88000.0),
    ('ING-KEM-NIGARI-FARM', 87000.0),
    ('ING-MASCAPON', 260000.0),
    ('ING-MAU-CAM-TUOI', 205714.29),
    ('ING-MAU-DA-IVORY', 205714.29),
    ('ING-MAU-DO-CHERRY', 205714.29),
    ('ING-MAU-HONG-DAU', 205714.29),
    ('ING-MAU-NAU-GO', 205714.29),
    ('ING-MAU-TIM-LAVENDER', 205714.29),
    ('ING-MAU-TIM-RASPERRY', 205714.29),
    ('ING-MAU-VANG-DAT', 205714.29),
    ('ING-MAU-XANH-DA-TROI', 205714.29),
    ('ING-MAU-XANH-REU', 205714.29),
    ('ING-MAU-XANH-TRAI-BO', 205714.29),
    ('ING-MY-CREAMS', 69000.0),
    ('ING-RUOU-KLUA', 642857.14),
    ('ING-SOCOLA-NUT-DEN', 365000.0),
    ('ING-WHIPPING', 146000.0),
    ('ING-YUM-CHERRY', 621000.0),
    ('ING-YUM-DAU', 621000.0),
    ('ING-DIA-SET-10', 64.0),
    ('ING-NEN-TANG-BANH-KEM', 10800.0),
    ('ING-TUI-SANDWICH', 148000.0),
    ('ING-TUI-SO-2', 68000.0),
    ('ING-TUI-SO-3', 63000.0),
    ('ING-HOP-BANH-FLAN', 400.0),
    ('ING-TRUNG-MUOI', 292857.14),
    ('ING-TUI-SO-1', 70000.0),
    ('ING-BERINO-DAU', 102000.0),
    ('ING-BERINO-VIET-QUAT', 119000.0),
    ('ING-BO-FE', 108000.0),
    ('ING-BOT-BAP', 28000.0),
    ('ING-BOT-TRA-XANH', 750000.0),
    ('ING-CHA-BONG-CAY', 155000.0),
    ('ING-CHA-BONG-TRANG', 145000.0),
    ('ING-CHA-BONG-VANG', 145000.0),
    ('ING-CHEESE', 188970.59),
    ('ING-GALENTINE-LA', 680000.0),
    ('ING-HANH-NHAN-LAT', 300000.0),
    ('ING-HOP-PANACOTTA', 320.0),
    ('ING-KEM-BAZE', 82000.0),
    ('ING-KEM-GOLD', 68000.0),
    ('ING-KEM-RICH-LUN', 68281.94),
    ('ING-KEM-VALUE-VANG', 59000.0),
    ('ING-MAU-DEN', 205714.29),
    ('ING-MAU-SIEU-DO', 205714.29),
    ('ING-MAU-VANG-TUOI', 205714.29),
    ('ING-SOCOLA-DEN', 124000.0),
    ('ING-SOCOLA-SET', 145250.0),
    ('ING-SOCOLA-TRANG', 116000.0),
    ('ING-SUA-TUOI', 29000.0),
    ('ING-BOT-CACAO', 174000.0),
    ('ING-BOT-KHOAI-LANG-TIM', 600000.0),
    ('ING-BOT-NANG', 36000.0),
    ('ING-BOT-NOI', 64000.0),
    ('ING-BOT-REDVELET', 105000.0),
    ('ING-BOT-CHIEN-XU', 75000.0),
    ('ING-BOT-DEO', 70000.0),
    ('ING-CHANH', 25000.0),
    ('ING-BOT-GAO', 45000.0),
    ('ING-BOT-KHAI', 50000.0),
    ('ING-BOT-NEP', 38000.0),
    ('ING-CAROT', 25000.0),
    ('ING-GAS-BO', 1620000.0),
    ('ING-DAU-AN', 37000.0),
    ('ING-DAU-ME', 200000.0),
    ('ING-DAU-SIMPLY', 55000.0),
    ('ING-DUA-BAO', 70000.0),
    ('ING-GAS-NHO', 330000.0),
    ('ING-HUONG-CHUOI', 2500.0),
    ('ING-HANH-LA', 12000.0),
    ('ING-MAJO', 120000.0),
    ('ING-MAU-DIEU', 260000.0),
    ('ING-HANH-TAY', 19000.0),
    ('ING-MUC', 220000.0),
    ('ING-MUOI', 7000.0),
    ('ING-HOP-THIEC-CHU-NHAT', 1650.0),
    ('ING-HOP-LAN-CHUOI', 1900.0),
    ('ING-OT-CHUONG', 40000.0),
    ('ING-TOM', 110000.0),
    ('ING-NUOC-XA-XIU', 17142.86),
    ('ING-PATE', 82857.14),
    ('ING-RONG-BIEN', 1500000.0),
    ('ING-DE-18', 4000.0),
    ('ING-DE-22', 6000.0),
    ('ING-DE-25', 7000.0),
    ('ING-SORTANING-25KG', 42600.0),
    ('ING-DE-28', 7000.0),
    ('ING-DE-30', 8000.0),
    ('ING-THIT-XA-XIU', 120000.0),
    ('ING-THIT-NHAN-BANH-BAO', 150000.0),
    ('ING-TUONG-CA', 50000.0),
    ('ING-VITMIN-C', 70000.0),
    ('ING-XUC-XICH', 70000.0),
    ('ING-XUC-XICH-CAT', 70000.0),
    ('ING-DUONG-DONUT', 50000.0),
    ('ING-BOT-CHONG-MOC', 150000.0),
    ('ING-NUOC-COT-DUA', 50000.0),
    ('ING-BICH-KIENG-20', 144.03),
    ('ING-DE-CHONG-TANG', 1000.0),
    ('ING-BO-HOP-BANH-18', 10000.0),
    ('ING-BO-HOP-BANH-22', 15000.0),
    ('ING-BO-HOP-BANH-26', 18000.0),
    ('ING-BO-HOP-BANH-3-TANG', 40000.0),
    ('ING-BO-HOP-BANH-34', 25000.0),
    ('ING-VANI', 220.0),
    ('ING-TRUNG-DANH-BOT', 700000.0),
    ('ING-HOP-H15-BAU', 850.0),
    ('ING-TAM-CHONG-TANG', 1000.0),
    ('ING-TRA-OLONG', 270000.0),
    ('ING-DE-32', 14000.0),
    ('ING-DE-35', 17000.0),
    ('ING-DE-40', 20000.0),
    ('ING-HOP-1-BANH', 2500.0),
    ('ING-HOP-18X18', 4000.0),
    ('ING-HOP-2-BANH', 4500.0),
    ('ING-HOP-22X20', 6000.0),
    ('ING-HOP-25X20', 7000.0),
    ('ING-HOP-28X20', 7500.0),
    ('ING-MUT-BAP', 80000.0),
    ('ING-NUOC-CHANH-DAY', 56000.0),
    ('ING-BICH-BANH-MI-DAI', 375.0),
    ('ING-BICH-DEP-20', 428.57),
    ('ING-BICH-DEP-24', 1000.0),
    ('ING-BICH-DEP-26', 1090.91),
    ('ING-BICH-KIENG-15-SW', 190.22),
    ('ING-BICH-XOP-50', 2647.06),
    ('ING-BICH-XOP-60', 3750.0),
    ('ING-HOP-3-BANH', 7500.0),
    ('ING-HOP-30X20', 8000.0),
    ('ING-HOP-30X25', 17000.0),
    ('ING-HOP-30X30', 17000.0),
    ('ING-HOP-32X20', 17000.0),
    ('ING-HOP-35X20', 17000.0),
    ('ING-HOP-35X25', 17000.0),
    ('ING-HOP-40X20', 20000.0),
    ('ING-HOP-BANH-BAO', 1200.0),
    ('ING-HOP-H24', 2500.0),
    ('ING-HOP-P500D', 2000.0),
    ('ING-HOP-HT203', 2200.0),
    ('ING-TUONG-CA-NHO', 250.0),
    ('ING-HOP-CRAF-CHU-NHAT', 1700.0),
    ('ING-HOP-TAM-GIAC', 1100.0),
    ('ING-TUI-VAI-0018', 6000.0),
    ('ING-TUI-VAI-2225', 7000.0),
    ('ING-TUI-VAI-2830', 7500.0),
    ('ING-NUOC-XIT-TAY-LO', 60000.0),
    ('ING-TUONG-OT-NHO', 250.0),
    ('ING-BICH-XOP-10', 803.57),
    ('ING-TUI-DAN-10', 70.92),
    ('ING-HOP-PET-500', 6800.0),
    ('ING-HOP-PET-750', 8200.0),
    ('ING-MUONG-NHO', 280.0),
    ('ING-BOT-PHO-MAI', 398000.0),
    ('ING-BOT-SUA', 116000.0),
    ('ING-BANG-KEO-LON', 25000.0),
    ('ING-BANG-KEO-MINI', 7000.0),
    ('ING-PHO-MAI-LAT', 375000.0),
    ('ING-PHOMAI-BO-CUOI', 5625.0),
    ('ING-BANG-KEO-SW', 8000.0),
    ('ING-SUA-CHUA-KHONG-DUONG', 6250.0),
    ('ING-SUA-DAC', 67000.0),
    ('ING-TRUNG-CUT', 700.0),
    ('ING-THOM-SEN', 50000.0),
    ('ING-TRUNG-VIT', 4000.0),
    ('ING-BAP-MY', 8000.0),
    ('ING-CHA', 110000.0),
    ('ING-CHUOI', 7000.0),
    ('ING-CU-SAN', 18000.0),
    ('ING-DA-BAO', 130000.0),
    ('ING-DAU-HA-LAN', 110000.0),
    ('ING-DAU-PHONG', 150000.0),
    ('ING-HANH-PHI', 120000.0),
    ('ING-HANH-TIM', 20000.0),
    ('ING-KHOAI-LANG', 45000.0),
    ('ING-LAP-XUONG', 160000.0),
    ('ING-ME-DEN', 120000.0),
    ('ING-ME-TRANG', 120000.0),
    ('ING-MO-HEO', 60000.0),
    ('ING-MUC-2', 220000.0),
    ('ING-MUT-BI', 90000.0),
    ('ING-THIT-XAY', 110000.0),
    ('ING-THOM-TRAI', 18000.0),
    ('ING-HANH-TAY-2', 20000.0),
    ('ING-HANH-LA-2', 15000.0),
    ('ING-BOT-BIEN-TINH', 115000.0),
    ('ING-BO-ANCHOR', 2800.0),
    ('ING-BO-NAUY', 160500.0),
    ('ING-BO-THE', 119000.0),
    ('ING-BO-THOM', 82000.0),
    ('ING-BO-TUONG-AN', 50000.0),
    ('ING-BOT-555', 18320.0),
    ('ING-BOT-BEO', 38000.0),
    ('ING-BOT-BH-25KG', 18000.0),
    ('ING-BOT-BH-XANH', 28000.0),
    ('ING-BOT-BUTTER-MILK', 310000.0),
    ('ING-BAO-TAM-GIAC', 83000.0),
    ('ING-CAY-DANH-BOT', 150000.0),
    ('ING-CAY-LAU-SAN', 125000.0),
    ('ING-BICH-PD-TU-BANH-BAO', 70000.0),
    ('ING-BOT-GIAT', 155000.0),
    ('ING-GIAY-LAN', 550000.0),
    ('ING-NUOC-LAU-SAN', 60000.0),
    ('ING-NUOC-RUA-CHEN', 150000.0),
    ('ING-THUN', 31000.0),
    ('ING-TUI-ZIP-0-5KG', 95000.0),
    ('ING-TUI-ZIP-1KG', 95000.0),
    ('ING-BAO-TAY-Y-TE', 1500.0),
    ('ING-XIEN-QUE', 80000.0),
    ('ING-XIEN-QUE-DONUT', 390.0),
    ('ING-KHAN-GIAY', 30000.0),
    ('ING-GIAY-SILICON', 175000.0),
    ('ING-BICH-BAT-SUKEM', 180000.0),
    ('ING-DAU-BAT-SUKEM', 45000.0),
    ('ING-CAY-VET-BOT', 38000.0),
    ('ING-CHOI', 66000.0),
    ('ING-CO-QUET', 40000.0),
    ('ING-DAY-COT-BANH', 60000.0),
    ('ING-DUNG-CU-HOT-RAC', 20000.0),
    ('ING-GHIM-BAM', 6500.0),
    ('ING-MIENG-LAU-SAN', 80000.0),
    ('ING-NUOC-LAU-KINH', 60000.0),
    ('ING-MANG-BOC-THUC-PHAM', 160000.0),
    ('ING-TUI-VAI-18', 8000.0),
    ('ING-TUI-VAI-22', 8600.0),
    ('ING-TUI-VAI-25', 8700.0),
    ('ING-TUI-VAI-2830-MOI', 9500.0),
    ('ING-TUI-VAI-3235', 14500.0)
) AS v(code, unit_cost)
WHERE item.code = v.code;

-- ── 6. ingredient_price — lịch sử giá, effective_date = ngày seed ─
-- ON CONFLICT: nếu cùng item + effective_date đã có, cập nhật giá
INSERT INTO ingredient_price (item_id, supplier_id, price, effective_date, status, approval_status)
SELECT i.id,
       (SELECT id FROM supplier WHERE code = v.supplier_code LIMIT 1),
       v.price, CURRENT_DATE, 'ACTIVE', 'APPROVED'
FROM (VALUES
    ('ING-HOP-A93', 'XN', 1100.0),
    ('ING-HOP-PENTO', 'TT', 1700.0),
    ('ING-DAO-BK', 'VD', 700.0),
    ('ING-GIAY-LOT-KHAY', 'SG', 473.0),
    ('ING-HOP-H128', 'TT', 650.0),
    ('ING-HOP-H19', 'TT', 1200.0),
    ('ING-HOP-CRAF-VUONG', 'TT', 1700.0),
    ('ING-HOP-H03', 'TT', 800.0),
    ('ING-NEN-0', 'VD', 800.0),
    ('ING-NEN-1', 'VD', 800.0),
    ('ING-NEN-2', 'VD', 800.0),
    ('ING-NEN-3', 'VD', 800.0),
    ('ING-NEN-4', 'VD', 800.0),
    ('ING-NEN-5', 'VD', 800.0),
    ('ING-NEN-6', 'VD', 800.0),
    ('ING-NEN-7', 'VD', 800.0),
    ('ING-NEN-8', 'VD', 800.0),
    ('ING-NEN-9', 'VD', 800.0),
    ('ING-NIA', 'SG', 120.0),
    ('ING-TUI-BANH-MI-HOA-CUC', 'SG', 866.67),
    ('ING-TUI-DONG-BANH-12-X-27', 'SG', 0.63),
    ('ING-TUI-DONG-BANH-15-X-22', 'SG', 500.0),
    ('ING-TUI-DONG-BANH-17-X-24', 'SG', 412.5),
    ('ING-TUI-LAN-TAM-GIAC', 'SG', 334.0),
    ('ING-CAFE-DEN-GOI', 'CHO', 4210.53),
    ('ING-TAM-TRE', 'CHO', 10000.0),
    ('ING-THUOC-TAY-CHA-SAN', 'CHO', 60000.0),
    ('ING-TUI-DUNG-RAC', 'CHO', 30000.0),
    ('ING-VI-CHA-NOI', 'CHO', 55000.0),
    ('ING-VIEM', 'CHO', 60000.0),
    ('ING-BAO-TAY-LEN-CAP', 'CHO', 5000.0),
    ('ING-BAO-TAY-LO', 'SG', 165000.0),
    ('ING-BOT-XE-DAP', 'VD', 15550.0),
    ('ING-DUONG-BOT', 'VD', 45000.0),
    ('ING-DUONG-CAT', 'CHO', 19200.0),
    ('ING-HUONG-DUA', 'VD', 125000.0),
    ('ING-HUONG-SUA', 'VD', 40000.0),
    ('ING-KEM-PHO-MAI', 'SON', 113000.0),
    ('ING-KEM-VIVO', 'VD', 79000.0),
    ('ING-MEN-LAT', 'VD', 116000.0),
    ('ING-MEN-NGOT', 'VD', 116000.0),
    ('ING-MUT-CAM-NHA-DAM', 'TGNL', 92000.0),
    ('ING-NHAN-DAU-XANH', 'VD', 79000.0),
    ('ING-NHAN-MON', 'VD', 80000.0),
    ('ING-NHO', 'TT', 102000.0),
    ('ING-PHOMAI-SOI', 'TGNL', 173000.0),
    ('ING-PHU-GIA-LAT', 'VD', 160000.0),
    ('ING-PHU-GIA-NGOT', 'VD', 98000.0),
    ('ING-SP-5KG', 'VD', 74000.0),
    ('ING-SU-KEM-1-KG', 'VD', 119000.0),
    ('ING-GALENTINE-BOT', 'TT', 300000.0),
    ('ING-CHEN-GIAY-SO-15', 'TT', 124.0),
    ('ING-CHEN-GIAY-SO-8', 'TT', 100.0),
    ('ING-GIAY-LOT-PENTO', 'SG', 300.0),
    ('ING-BOT-TARTA', NULL, 192592.59),
    ('ING-GODEN-FARM-CHANH-DAY', 'XN', 106000.0),
    ('ING-GODEN-FARM-KIWI', 'XN', 100000.0),
    ('ING-HUONG-BAP', 'VD', 310000.0),
    ('ING-KEM-MAN', 'SON', 88000.0),
    ('ING-KEM-NIGARI-FARM', 'SON', 87000.0),
    ('ING-MASCAPON', 'XN', 260000.0),
    ('ING-MAU-CAM-TUOI', 'SG', 205714.29),
    ('ING-MAU-DA-IVORY', 'SG', 205714.29),
    ('ING-MAU-DO-CHERRY', 'SG', 205714.29),
    ('ING-MAU-HONG-DAU', 'SG', 205714.29),
    ('ING-MAU-NAU-GO', 'SG', 205714.29),
    ('ING-MAU-TIM-LAVENDER', 'SG', 205714.29),
    ('ING-MAU-TIM-RASPERRY', 'SG', 205714.29),
    ('ING-MAU-VANG-DAT', 'SG', 205714.29),
    ('ING-MAU-XANH-DA-TROI', 'SG', 205714.29),
    ('ING-MAU-XANH-REU', 'SG', 205714.29),
    ('ING-MAU-XANH-TRAI-BO', 'SG', 205714.29),
    ('ING-MY-CREAMS', 'SON', 69000.0),
    ('ING-RUOU-KLUA', 'TT', 642857.14),
    ('ING-SOCOLA-NUT-DEN', 'XN', 365000.0),
    ('ING-WHIPPING', 'TGNL', 146000.0),
    ('ING-YUM-CHERRY', 'SG', 621000.0),
    ('ING-YUM-DAU', 'SG', 621000.0),
    ('ING-DIA-SET-10', 'SG', 64.0),
    ('ING-NEN-TANG-BANH-KEM', 'SG', 10800.0),
    ('ING-TUI-SANDWICH', 'SG', 148000.0),
    ('ING-TUI-SO-2', 'SG', 68000.0),
    ('ING-TUI-SO-3', 'SG', 63000.0),
    ('ING-HOP-BANH-FLAN', 'TGNL', 400.0),
    ('ING-TRUNG-MUOI', 'TT', 292857.14),
    ('ING-TUI-SO-1', 'SG', 70000.0),
    ('ING-BERINO-DAU', 'XN', 102000.0),
    ('ING-BERINO-VIET-QUAT', 'TT', 119000.0),
    ('ING-BO-FE', 'VD', 108000.0),
    ('ING-BOT-BAP', 'TT', 28000.0),
    ('ING-BOT-TRA-XANH', 'TGNL', 750000.0),
    ('ING-CHA-BONG-CAY', 'SG', 155000.0),
    ('ING-CHA-BONG-TRANG', 'SG', 145000.0),
    ('ING-CHA-BONG-VANG', 'SG', 145000.0),
    ('ING-CHEESE', 'SON', 188970.59),
    ('ING-GALENTINE-LA', 'XN', 680000.0),
    ('ING-HANH-NHAN-LAT', 'TT', 300000.0),
    ('ING-HOP-PANACOTTA', 'TT', 320.0),
    ('ING-KEM-BAZE', 'SON', 82000.0),
    ('ING-KEM-GOLD', 'SON', 68000.0),
    ('ING-KEM-RICH-LUN', 'SON', 68281.94),
    ('ING-KEM-VALUE-VANG', 'SON', 59000.0),
    ('ING-MAU-DEN', 'SG', 205714.29),
    ('ING-MAU-SIEU-DO', 'SG', 205714.29),
    ('ING-MAU-VANG-TUOI', 'SG', 205714.29),
    ('ING-SOCOLA-DEN', 'XN', 124000.0),
    ('ING-SOCOLA-SET', 'VD', 145250.0),
    ('ING-SOCOLA-TRANG', 'XN', 116000.0),
    ('ING-SUA-TUOI', 'TGNL', 29000.0),
    ('ING-BOT-CACAO', 'TT', 174000.0),
    ('ING-BOT-KHOAI-LANG-TIM', 'XN', 600000.0),
    ('ING-BOT-NANG', 'TT', 36000.0),
    ('ING-BOT-NOI', 'VD', 64000.0),
    ('ING-BOT-REDVELET', 'VD', 105000.0),
    ('ING-BOT-CHIEN-XU', 'CHO', 75000.0),
    ('ING-BOT-DEO', 'TT', 70000.0),
    ('ING-CHANH', NULL, 25000.0),
    ('ING-BOT-GAO', 'TT', 45000.0),
    ('ING-BOT-KHAI', 'TT', 50000.0),
    ('ING-BOT-NEP', 'TT', 38000.0),
    ('ING-CAROT', 'CHO', 25000.0),
    ('ING-GAS-BO', 'CHO', 1620000.0),
    ('ING-DAU-AN', 'CHO', 37000.0),
    ('ING-DAU-ME', 'CHO', 200000.0),
    ('ING-DAU-SIMPLY', 'CHO', 55000.0),
    ('ING-DUA-BAO', 'CHO', 70000.0),
    ('ING-GAS-NHO', 'CHO', 330000.0),
    ('ING-HUONG-CHUOI', 'CHO', 2500.0),
    ('ING-HANH-LA', 'CHO', 12000.0),
    ('ING-MAJO', 'CHO', 120000.0),
    ('ING-MAU-DIEU', 'CHO', 260000.0),
    ('ING-HANH-TAY', 'CHO', 19000.0),
    ('ING-MUC', 'CHO', 220000.0),
    ('ING-MUOI', 'CHO', 7000.0),
    ('ING-HOP-THIEC-CHU-NHAT', 'TT', 1650.0),
    ('ING-HOP-LAN-CHUOI', 'SG', 1900.0),
    ('ING-OT-CHUONG', 'CHO', 40000.0),
    ('ING-TOM', 'CHO', 110000.0),
    ('ING-NUOC-XA-XIU', 'CHO', 17142.86),
    ('ING-PATE', 'CHO', 82857.14),
    ('ING-RONG-BIEN', 'CHO', 1500000.0),
    ('ING-DE-18', 'SG', 4000.0),
    ('ING-DE-22', 'SG', 6000.0),
    ('ING-DE-25', 'SG', 7000.0),
    ('ING-SORTANING-25KG', 'VD', 42600.0),
    ('ING-DE-28', 'SG', 7000.0),
    ('ING-DE-30', 'SG', 8000.0),
    ('ING-THIT-XA-XIU', 'CHO', 120000.0),
    ('ING-THIT-NHAN-BANH-BAO', 'CHO', 150000.0),
    ('ING-TUONG-CA', 'CHO', 50000.0),
    ('ING-VITMIN-C', 'TT', 70000.0),
    ('ING-XUC-XICH', 'CHO', 70000.0),
    ('ING-XUC-XICH-CAT', 'CHO', 70000.0),
    ('ING-DUONG-DONUT', 'SG', 50000.0),
    ('ING-BOT-CHONG-MOC', 'SG', 150000.0),
    ('ING-NUOC-COT-DUA', NULL, 50000.0),
    ('ING-BICH-KIENG-20', 'CHO', 144.03),
    ('ING-DE-CHONG-TANG', 'VD', 1000.0),
    ('ING-BO-HOP-BANH-18', 'CHO', 10000.0),
    ('ING-BO-HOP-BANH-22', 'CHO', 15000.0),
    ('ING-BO-HOP-BANH-26', 'CHO', 18000.0),
    ('ING-BO-HOP-BANH-3-TANG', 'CHO', 40000.0),
    ('ING-BO-HOP-BANH-34', 'CHO', 25000.0),
    ('ING-VANI', 'CHO', 220.0),
    ('ING-TRUNG-DANH-BOT', 'CHO', 700000.0),
    ('ING-HOP-H15-BAU', 'TT', 850.0),
    ('ING-TAM-CHONG-TANG', 'VD', 1000.0),
    ('ING-TRA-OLONG', 'TT', 270000.0),
    ('ING-DE-32', 'SG', 14000.0),
    ('ING-DE-35', 'SG', 17000.0),
    ('ING-DE-40', 'SG', 20000.0),
    ('ING-HOP-1-BANH', 'SG', 2500.0),
    ('ING-HOP-18X18', 'SG', 4000.0),
    ('ING-HOP-2-BANH', 'SG', 4500.0),
    ('ING-HOP-22X20', 'SG', 6000.0),
    ('ING-HOP-25X20', 'SG', 7000.0),
    ('ING-HOP-28X20', 'SG', 7500.0),
    ('ING-MUT-BAP', 'CHO', 80000.0),
    ('ING-NUOC-CHANH-DAY', 'CHO', 56000.0),
    ('ING-BICH-BANH-MI-DAI', 'CHO', 375.0),
    ('ING-BICH-DEP-20', 'CHO', 428.57),
    ('ING-BICH-DEP-24', 'CHO', 1000.0),
    ('ING-BICH-DEP-26', 'CHO', 1090.91),
    ('ING-BICH-KIENG-15-SW', 'CHO', 190.22),
    ('ING-BICH-XOP-50', 'CHO', 2647.06),
    ('ING-BICH-XOP-60', 'CHO', 3750.0),
    ('ING-HOP-3-BANH', 'SG', 7500.0),
    ('ING-HOP-30X20', 'SG', 8000.0),
    ('ING-HOP-30X25', 'SG', 17000.0),
    ('ING-HOP-30X30', 'SG', 17000.0),
    ('ING-HOP-32X20', 'SG', 17000.0),
    ('ING-HOP-35X20', 'SG', 17000.0),
    ('ING-HOP-35X25', 'SG', 17000.0),
    ('ING-HOP-40X20', 'SG', 20000.0),
    ('ING-HOP-BANH-BAO', 'CHO', 1200.0),
    ('ING-HOP-H24', 'VD', 2500.0),
    ('ING-HOP-P500D', 'CHO', 2000.0),
    ('ING-HOP-HT203', 'TT', 2200.0),
    ('ING-TUONG-CA-NHO', 'CHO', 250.0),
    ('ING-HOP-CRAF-CHU-NHAT', 'TT', 1700.0),
    ('ING-HOP-TAM-GIAC', 'VD', 1100.0),
    ('ING-TUI-VAI-0018', 'SG', 6000.0),
    ('ING-TUI-VAI-2225', 'SG', 7000.0),
    ('ING-TUI-VAI-2830', 'SG', 7500.0),
    ('ING-NUOC-XIT-TAY-LO', 'CHO', 60000.0),
    ('ING-TUONG-OT-NHO', 'CHO', 250.0),
    ('ING-BICH-XOP-10', 'CHO', 803.57),
    ('ING-TUI-DAN-10', 'CHO', 70.92),
    ('ING-HOP-PET-500', 'XN', 6800.0),
    ('ING-HOP-PET-750', 'XN', 8200.0),
    ('ING-MUONG-NHO', 'TGNL', 280.0),
    ('ING-BOT-PHO-MAI', 'TT', 398000.0),
    ('ING-BOT-SUA', 'TGNL', 116000.0),
    ('ING-BANG-KEO-LON', 'CHO', 25000.0),
    ('ING-BANG-KEO-MINI', 'CHO', 7000.0),
    ('ING-PHO-MAI-LAT', 'CHO', 375000.0),
    ('ING-PHOMAI-BO-CUOI', 'CHO', 5625.0),
    ('ING-BANG-KEO-SW', 'CHO', 8000.0),
    ('ING-SUA-CHUA-KHONG-DUONG', 'CHO', 6250.0),
    ('ING-SUA-DAC', 'CHO', 67000.0),
    ('ING-TRUNG-CUT', NULL, 700.0),
    ('ING-THOM-SEN', 'CHO', 50000.0),
    ('ING-TRUNG-VIT', NULL, 4000.0),
    ('ING-BAP-MY', NULL, 8000.0),
    ('ING-CHA', NULL, 110000.0),
    ('ING-CHUOI', NULL, 7000.0),
    ('ING-CU-SAN', NULL, 18000.0),
    ('ING-DA-BAO', NULL, 130000.0),
    ('ING-DAU-HA-LAN', NULL, 110000.0),
    ('ING-DAU-PHONG', NULL, 150000.0),
    ('ING-HANH-PHI', NULL, 120000.0),
    ('ING-HANH-TIM', NULL, 20000.0),
    ('ING-KHOAI-LANG', NULL, 45000.0),
    ('ING-LAP-XUONG', NULL, 160000.0),
    ('ING-ME-DEN', NULL, 120000.0),
    ('ING-ME-TRANG', NULL, 120000.0),
    ('ING-MO-HEO', NULL, 60000.0),
    ('ING-MUC-2', NULL, 220000.0),
    ('ING-MUT-BI', NULL, 90000.0),
    ('ING-THIT-XAY', NULL, 110000.0),
    ('ING-THOM-TRAI', NULL, 18000.0),
    ('ING-HANH-TAY-2', NULL, 20000.0),
    ('ING-HANH-LA-2', 'CHO', 15000.0),
    ('ING-BOT-BIEN-TINH', 'TT', 115000.0),
    ('ING-BO-ANCHOR', 'TGNL', 2800.0),
    ('ING-BO-NAUY', 'VD', 160500.0),
    ('ING-BO-THE', 'TT', 119000.0),
    ('ING-BO-THOM', 'VD', 82000.0),
    ('ING-BO-TUONG-AN', 'VD', 50000.0),
    ('ING-BOT-555', 'VD', 18320.0),
    ('ING-BOT-BEO', 'TT', 38000.0),
    ('ING-BOT-BH-25KG', 'TT', 18000.0),
    ('ING-BOT-BH-XANH', 'TT', 28000.0),
    ('ING-BOT-BUTTER-MILK', 'VD', 310000.0),
    ('ING-BAO-TAM-GIAC', 'VD', 83000.0),
    ('ING-CAY-DANH-BOT', 'CHO', 150000.0),
    ('ING-CAY-LAU-SAN', 'CHO', 125000.0),
    ('ING-BICH-PD-TU-BANH-BAO', 'CHO', 70000.0),
    ('ING-BOT-GIAT', 'CHO', 155000.0),
    ('ING-GIAY-LAN', 'CHO', 550000.0),
    ('ING-NUOC-LAU-SAN', 'CHO', 60000.0),
    ('ING-NUOC-RUA-CHEN', 'CHO', 150000.0),
    ('ING-THUN', 'CHO', 31000.0),
    ('ING-TUI-ZIP-0-5KG', 'CHO', 95000.0),
    ('ING-TUI-ZIP-1KG', 'CHO', 95000.0),
    ('ING-BAO-TAY-Y-TE', 'CHO', 1500.0),
    ('ING-XIEN-QUE', 'CHO', 80000.0),
    ('ING-XIEN-QUE-DONUT', 'SG', 390.0),
    ('ING-KHAN-GIAY', 'CHO', 30000.0),
    ('ING-GIAY-SILICON', 'SG', 175000.0),
    ('ING-BICH-BAT-SUKEM', 'SG', 180000.0),
    ('ING-DAU-BAT-SUKEM', 'SG', 45000.0),
    ('ING-CAY-VET-BOT', 'CHO', 38000.0),
    ('ING-CHOI', 'CHO', 66000.0),
    ('ING-CO-QUET', 'CHO', 40000.0),
    ('ING-DAY-COT-BANH', 'CHO', 60000.0),
    ('ING-DUNG-CU-HOT-RAC', 'CHO', 20000.0),
    ('ING-GHIM-BAM', 'CHO', 6500.0),
    ('ING-MIENG-LAU-SAN', 'CHO', 80000.0),
    ('ING-NUOC-LAU-KINH', 'CHO', 60000.0),
    ('ING-MANG-BOC-THUC-PHAM', 'CHO', 160000.0),
    ('ING-TUI-VAI-18', 'SG', 8000.0),
    ('ING-TUI-VAI-22', 'SG', 8600.0),
    ('ING-TUI-VAI-25', 'SG', 8700.0),
    ('ING-TUI-VAI-2830-MOI', 'SG', 9500.0),
    ('ING-TUI-VAI-3235', 'SG', 14500.0)
) AS v(item_code, supplier_code, price)
JOIN item i ON i.code = v.item_code
WHERE NOT EXISTS (
    SELECT 1 FROM ingredient_price ip
    WHERE ip.item_id = i.id AND ip.effective_date = CURRENT_DATE
);