-- ============================================================
-- Insert data: Supplier + Ingredient (item_type=INGREDIENT) + IngredientPrice
-- Nguồn: DS HÀNG NHẬP 2026.xlsx (Sheet1, 345 dòng; Sheet2 bỏ qua vì trùng tên Sheet1)
-- Schema: single-table inheritance trên bảng item (com.bakery.api.master.entity.Item)
-- DB: PostgreSQL
-- ============================================================

-- 1) code_value: INGREDIENT_TYPE (dùng tên category trong file làm phân loại nguyên liệu)
INSERT INTO code_value (group_key, code, name, sort_order) VALUES
  ('INGREDIENT_TYPE', 'BÁN HÀNG', 'BÁN HÀNG', 1),
  ('INGREDIENT_TYPE', 'BÁNH MÌ', 'BÁNH MÌ', 2),
  ('INGREDIENT_TYPE', 'HÀNG CHỢ', 'HÀNG CHỢ', 3),
  ('INGREDIENT_TYPE', 'HÀNG SỬ DỤNG CHUNG', 'HÀNG SỬ DỤNG CHUNG', 4),
  ('INGREDIENT_TYPE', 'PHA CHẾ', 'PHA CHẾ', 5),
  ('INGREDIENT_TYPE', 'PHÒNG LẠNH', 'PHÒNG LẠNH', 6)
ON CONFLICT DO NOTHING;

-- 2) supplier (7 mã viết tắt từ cột H — tên tạm = mã viết tắt, cần cập nhật đầy đủ contact_name/phone/address sau)
INSERT INTO supplier (code, name) VALUES
  ('CHO', 'CHỢ'),
  ('SG', 'SG'),
  ('VD', 'VD'),
  ('TT', 'TT'),
  ('XN', 'XN'),
  ('TGNL', 'TGNL'),
  ('SON', 'SƠN')
ON CONFLICT (code) DO NOTHING;

-- 3) item (item_type=INGREDIENT, 345 dòng, CODE tự sinh ING-<TÊN-KHÔNG-DẤU>)
INSERT INTO item (item_type, code, name, unit, ingredient_type, default_supplier_id)
SELECT 'INGREDIENT', v.code, v.name, v.unit, v.category, s.id
FROM (VALUES
  ('ING-BO-ANCHOR', 'bơ anchor', 'KG', 'BÁNH MÌ', 'TGNL'),
  ('ING-BO-NAUY', 'bơ nauy', 'KG', 'BÁNH MÌ', 'VD'),
  ('ING-BO-THE', 'bơ thẻ', 'KG', 'BÁNH MÌ', 'TT'),
  ('ING-BO-THOM', 'bơ thơm', 'KG', 'BÁNH MÌ', 'VD'),
  ('ING-BO-TUONG-AN', 'bơ tường an', 'KG', 'BÁNH MÌ', 'VD'),
  ('ING-BOT-555', 'bột 555', 'KG', 'BÁNH MÌ', 'VD'),
  ('ING-BOT-BEO', 'bột béo', 'KG', 'BÁNH MÌ', 'TT'),
  ('ING-BOT-BH-25KG', 'bột bh 25kg', 'KG', 'BÁNH MÌ', 'TT'),
  ('ING-BOT-BH-XANH', 'bột bh xanh', 'KG', 'BÁNH MÌ', 'TT'),
  ('ING-BOT-BIEN-TINH', 'bột biến tính', 'KG', 'BÁNH MÌ', 'TT'),
  ('ING-BOT-BUTTER-MILK', 'bột butter milk', 'KG', 'BÁNH MÌ', 'VD'),
  ('ING-BOT-CACAO', 'bột cacao', 'KG', 'BÁNH MÌ', 'TT'),
  ('ING-BOT-CHIEN-XU', 'bột chiên xù', 'KG', 'BÁNH MÌ', 'CHO'),
  ('ING-BOT-DEO', 'bột dẻo', 'KG', 'BÁNH MÌ', 'TT'),
  ('ING-BOT-GAO', 'bột gạo', 'KG', 'BÁNH MÌ', 'TT'),
  ('ING-BOT-KHAI', 'bột khai', 'KG', 'BÁNH MÌ', 'TT'),
  ('ING-BOT-KHOAI-LANG-TIM', 'bột khoai lang tím', 'KG', 'BÁNH MÌ', 'XN'),
  ('ING-BOT-NANG', 'bột năng', 'KG', 'BÁNH MÌ', 'TT'),
  ('ING-BOT-NEP', 'bột nếp', 'KG', 'BÁNH MÌ', 'TT'),
  ('ING-BOT-NOI', 'bột nổi', 'KG', 'BÁNH MÌ', 'VD'),
  ('ING-BOT-REDVELET', 'bột redvelet', 'KG', 'BÁNH MÌ', 'VD'),
  ('ING-BOT-TARTA', 'bột tarta', 'KG', 'BÁNH MÌ', 'VD'),
  ('ING-BOT-XE-DAP', 'bột xe đạp', 'KG', 'BÁNH MÌ', 'VD'),
  ('ING-CAROT', 'carot', 'KG', 'BÁNH MÌ', 'CHO'),
  ('ING-CHEN-GIAY-SO-15', 'chén giấy số 15', 'CÁI', 'BÁNH MÌ', 'TT'),
  ('ING-CHEN-GIAY-SO-8', 'chén giấy số 8', 'CÁI', 'BÁNH MÌ', 'TT'),
  ('ING-DA-BAO-CHA', 'da bao chả', 'CÁI', 'BÁNH MÌ', 'CHO'),
  ('ING-DAU-AN', 'dầu ăn', 'KG', 'BÁNH MÌ', 'CHO'),
  ('ING-DAU-ME', 'dầu mè', 'KG', 'BÁNH MÌ', 'CHO'),
  ('ING-DAU-SIMPLY', 'dầu simply', 'KG', 'BÁNH MÌ', 'CHO'),
  ('ING-DUA-BAO', 'dừa bào', 'KG', 'BÁNH MÌ', 'CHO'),
  ('ING-DUONG-BOT', 'đường bột', 'KG', 'BÁNH MÌ', 'VD'),
  ('ING-DUONG-CAT', 'đường cát', 'KG', 'BÁNH MÌ', 'CHO'),
  ('ING-GAS-BO', 'gas bò', 'BÌNH', 'BÁNH MÌ', 'CHO'),
  ('ING-GAS-NHO', 'gas nhỏ', 'BÌNH', 'BÁNH MÌ', 'CHO'),
  ('ING-HANH-LA', 'hành lá', 'KG', 'BÁNH MÌ', 'CHO'),
  ('ING-HANH-TAY', 'hành tây', 'KG', 'BÁNH MÌ', 'CHO'),
  ('ING-HOP-THIEC-CHU-NHAT', 'hộp thiếc chữ nhật', 'CÁI', 'BÁNH MÌ', 'TT'),
  ('ING-HOP-LAN-CHUOI', 'hộp lan chuối', 'KG', 'BÁNH MÌ', 'SG'),
  ('ING-HUONG-CHUOI', 'hương chuối', 'ỐNG', 'BÁNH MÌ', 'CHO'),
  ('ING-HUONG-DUA', 'hương dứa', 'KG', 'BÁNH MÌ', 'VD'),
  ('ING-HUONG-SUA', 'hương sữa', 'KG', 'BÁNH MÌ', 'VD'),
  ('ING-KEM-PHO-MAI', 'kem phô mai', 'KG', 'BÁNH MÌ', 'SON'),
  ('ING-KEM-VIVO', 'kem vivo', 'KG', 'BÁNH MÌ', 'VD'),
  ('ING-MACH-NHA', 'mạch nha', 'KG', 'BÁNH MÌ', 'TT'),
  ('ING-MAJO', 'majo', 'KG', 'BÁNH MÌ', 'CHO'),
  ('ING-MAU-DIEU', 'màu điều', 'KG', 'BÁNH MÌ', 'CHO'),
  ('ING-MEN-LAT', 'men lạt', 'KG', 'BÁNH MÌ', 'VD'),
  ('ING-MEN-NGOT', 'men ngọt', 'KG', 'BÁNH MÌ', 'VD'),
  ('ING-MUC', 'mực', 'KG', 'BÁNH MÌ', 'CHO'),
  ('ING-MUOI', 'muối', 'KG', 'BÁNH MÌ', 'CHO'),
  ('ING-MUT-CAM-NHA-DAM', 'mứt cam nha đam', 'KG', 'BÁNH MÌ', 'TGNL'),
  ('ING-NHAN-DAU-XANH', 'nhân đậu xanh', 'KG', 'BÁNH MÌ', 'VD'),
  ('ING-NHAN-DUA', 'nhân dừa', 'KG', 'BÁNH MÌ', 'VD'),
  ('ING-NHAN-MON', 'nhân môn', 'KG', 'BÁNH MÌ', 'VD'),
  ('ING-NHAN-TRON', 'nhân trộn', 'KG', 'BÁNH MÌ', 'CHO'),
  ('ING-NHO', 'nho', 'KG', 'BÁNH MÌ', 'TT'),
  ('ING-NUOC-XA-XIU', 'nước xá xíu', 'KG', 'BÁNH MÌ', 'CHO'),
  ('ING-OT-CHUONG', 'ớt chuông', 'CÁI', 'BÁNH MÌ', 'CHO'),
  ('ING-PATE', 'pate', 'KG', 'BÁNH MÌ', 'CHO'),
  ('ING-RONG-BIEN', 'rong biển', 'KG', 'BÁNH MÌ', 'CHO'),
  ('ING-PHOMAI-SOI', 'phomai sợi', 'KG', 'BÁNH MÌ', 'TGNL'),
  ('ING-PHU-GIA-LAT', 'phụ gia lạt', 'KG', 'BÁNH MÌ', 'VD'),
  ('ING-PHU-GIA-NGOT', 'phụ gia ngọt', 'KG', 'BÁNH MÌ', 'VD'),
  ('ING-SAU-RIENG-KEM', 'sầu riêng kem', 'KG', 'BÁNH MÌ', NULL),
  ('ING-SORTANING-25KG', 'sortaning ( 25kg)', 'KG', 'BÁNH MÌ', 'VD'),
  ('ING-SP-5KG', 'sp (5kg)', 'KG', 'BÁNH MÌ', 'VD'),
  ('ING-SU-KEM-1-KG', 'su kem 1 kg', 'KG', 'BÁNH MÌ', 'VD'),
  ('ING-THIT-XA-XIU', 'thịt  xá xíu', 'KG', 'BÁNH MÌ', 'CHO'),
  ('ING-THIT-NHAN-BANH-BAO', 'thịt nhân bánh bao', 'KG', 'BÁNH MÌ', 'CHO'),
  ('ING-TOM', 'tôm', 'CÁI', 'BÁNH MÌ', 'CHO'),
  ('ING-TRUNG-DANH-BOT', 'trứng đánh bột', 'QUẢ', 'BÁNH MÌ', 'CHO'),
  ('ING-TUONG-CA', 'tương cà', 'KG', 'BÁNH MÌ', 'CHO'),
  ('ING-VANI', 'vani', 'ỐNG', 'BÁNH MÌ', 'CHO'),
  ('ING-VITMIN-C', 'vitmin c', 'KG', 'BÁNH MÌ', 'TT'),
  ('ING-XUC-XICH', 'xúc xích', 'KG', 'BÁNH MÌ', 'CHO'),
  ('ING-XUC-XICH-CAT', 'xúc xích cắt', 'KG', 'BÁNH MÌ', 'CHO'),
  ('ING-DUONG-DONUT', 'đường donut', 'KG', 'BÁNH MÌ', 'SG'),
  ('ING-BOT-CHONG-MOC', 'bột chống móc', 'KG', 'BÁNH MÌ', 'SG'),
  ('ING-NUOC-COT-DUA', 'nước cốt dừa', 'KG', 'BÁNH MÌ', NULL),
  ('ING-BICH-KIENG-20', 'bịch kiếng 20', 'KG', 'PHÒNG LẠNH', 'CHO'),
  ('ING-BO-HOP-BANH-18', 'bộ hộp bánh 18', 'BỘ', 'PHÒNG LẠNH', 'CHO'),
  ('ING-BO-HOP-BANH-22', 'bộ hộp bánh 22', 'BỘ', 'PHÒNG LẠNH', 'CHO'),
  ('ING-BO-HOP-BANH-26', 'bộ hộp bánh 26', 'BỘ', 'PHÒNG LẠNH', 'CHO'),
  ('ING-BO-HOP-BANH-3-TANG', 'bộ hộp bánh 3 tầng', 'BỘ', 'PHÒNG LẠNH', 'CHO'),
  ('ING-BO-HOP-BANH-34', 'bộ hộp bánh 34', 'BỘ', 'PHÒNG LẠNH', 'CHO'),
  ('ING-BOT-CACAO-TIRA', 'bột cacao (tira)', 'KG', 'PHÒNG LẠNH', NULL),
  ('ING-BOT-TRA-XANH-COSY', 'bột trà xanh cosy', 'KG', 'PHÒNG LẠNH', 'TGNL'),
  ('ING-DE-18', 'đế 18', 'CÁI', 'PHÒNG LẠNH', 'SG'),
  ('ING-DE-22', 'đế 22', 'CÁI', 'PHÒNG LẠNH', 'SG'),
  ('ING-DE-25', 'đế 25', 'CÁI', 'PHÒNG LẠNH', 'SG'),
  ('ING-DE-28', 'đế 28', 'CÁI', 'PHÒNG LẠNH', 'SG'),
  ('ING-DE-30', 'đế 30', 'CÁI', 'PHÒNG LẠNH', 'SG'),
  ('ING-DE-CHONG-TANG', 'đế chồng tầng', 'CÁI', 'PHÒNG LẠNH', 'VD'),
  ('ING-GALENTINE-BOT', 'galentine bột', 'KG', 'PHÒNG LẠNH', 'TT'),
  ('ING-GIAY-LOT-PENTO', 'giấy lót pento', 'CÁI', 'PHÒNG LẠNH', 'SG'),
  ('ING-GODEN-FARM-CHANH-DAY', 'goden farm chanh dây', 'KG', 'PHÒNG LẠNH', 'XN'),
  ('ING-GODEN-FARM-KIWI', 'goden farm kiwi', 'KG', 'PHÒNG LẠNH', 'XN'),
  ('ING-HOP-A93', 'hộp A93', 'CÁI', 'PHÒNG LẠNH', 'XN'),
  ('ING-HOP-BLTM-E1685', 'hộp bltm( E1685)', 'CÁI', 'PHÒNG LẠNH', 'SG'),
  ('ING-HOP-H15-BAU', 'hộp H15 bầu', 'CÁI', 'PHÒNG LẠNH', 'TT'),
  ('ING-HOP-PENTO', 'hộp pento', 'CÁI', 'PHÒNG LẠNH', 'TT'),
  ('ING-HOP-TIRA-TIM', 'hộp tira tim', 'CÁI', 'PHÒNG LẠNH', 'SG'),
  ('ING-HOP-TIRA-VUONG', 'hộp tira vuông', 'CÁI', 'PHÒNG LẠNH', 'SG'),
  ('ING-HUONG-BAP', 'hương bắp', 'KG', 'PHÒNG LẠNH', 'VD'),
  ('ING-KEM-MAN', 'kem mặn', 'KG', 'PHÒNG LẠNH', 'SON'),
  ('ING-KEM-NIGARI-FARM', 'kem nigari farm', 'KG', 'PHÒNG LẠNH', 'SON'),
  ('ING-LY-MIX-VI-5550', 'ly mix vị(5550)', 'CÁI', 'PHÒNG LẠNH', 'SG'),
  ('ING-MASCAPON', 'mascapon', 'KG', 'PHÒNG LẠNH', 'XN'),
  ('ING-MAU-CAM-TUOI', 'màu cam tươi', 'KG', 'PHÒNG LẠNH', 'SG'),
  ('ING-MAU-DA-IVORY', 'màu da ivory', 'KG', 'PHÒNG LẠNH', 'SG'),
  ('ING-MAU-DO-CHERRY', 'màu đỏ cherry', 'KG', 'PHÒNG LẠNH', 'SG'),
  ('ING-MAU-HONG-DAU', 'màu hồng dâu', 'KG', 'PHÒNG LẠNH', 'SG'),
  ('ING-MAU-NAU-GO', 'màu nâu gỗ', 'KG', 'PHÒNG LẠNH', 'SG'),
  ('ING-MAU-TIM-LAVENDER', 'màu tím lavender', 'KG', 'PHÒNG LẠNH', 'SG'),
  ('ING-MAU-TIM-RASPERRY', 'màu tím rasperry', 'KG', 'PHÒNG LẠNH', 'SG'),
  ('ING-MAU-VANG-DAT', 'màu vàng đất', 'KG', 'PHÒNG LẠNH', 'SG'),
  ('ING-MAU-XANH-DA-TROI', 'màu xanh da trời', 'KG', 'PHÒNG LẠNH', 'SG'),
  ('ING-MAU-XANH-REU', 'màu xanh rêu', 'KG', 'PHÒNG LẠNH', 'SG'),
  ('ING-MAU-XANH-TRAI-BO', 'màu xanh trái bơ', 'KG', 'PHÒNG LẠNH', 'SG'),
  ('ING-MUT-BAP', 'mứt bắp', 'KG', 'PHÒNG LẠNH', 'CHO'),
  ('ING-MY-CREAMS', 'my creams', 'KG', 'PHÒNG LẠNH', 'SON'),
  ('ING-NUOC-CHANH-DAY', 'nước chanh dây', 'KG', 'PHÒNG LẠNH', 'CHO'),
  ('ING-RUOU-KLUA', 'rượu klua', 'KG', 'PHÒNG LẠNH', 'TT'),
  ('ING-SOCOLA-NUT-DEN', 'socola nut đen', 'KG', 'PHÒNG LẠNH', 'XN'),
  ('ING-TAM-CHONG-TANG', 'tăm chống tầng', 'CÁI', 'PHÒNG LẠNH', 'VD'),
  ('ING-TRA-OLONG', 'trà olong', 'CÁI', 'PHÒNG LẠNH', 'TT'),
  ('ING-WHIPPING', 'whipping', 'KG', 'PHÒNG LẠNH', 'TGNL'),
  ('ING-YUM-CHERRY', 'yum cherry', 'KG', 'PHÒNG LẠNH', 'SG'),
  ('ING-YUM-DAU', 'yum dâu', 'KG', 'PHÒNG LẠNH', 'SG'),
  ('ING-BICH-BANH-MI-DAI', 'bịch bánh mì dài', 'KG', 'BÁN HÀNG', 'CHO'),
  ('ING-BICH-DEP-20', 'bịch đẹp 20', 'KG', 'BÁN HÀNG', 'CHO'),
  ('ING-BICH-DEP-24', 'bịch đẹp 24', 'KG', 'BÁN HÀNG', 'CHO'),
  ('ING-BICH-DEP-26', 'bịch đẹp 26', 'KG', 'BÁN HÀNG', 'CHO'),
  ('ING-BICH-KIENG-15-SW', 'bịch kiếng 15 (sw)', 'KG', 'BÁN HÀNG', 'CHO'),
  ('ING-BICH-XOP-50', 'bịch xốp 50', 'KG', 'BÁN HÀNG', 'CHO'),
  ('ING-BICH-XOP-60', 'bịch xốp 60', 'KG', 'BÁN HÀNG', 'CHO'),
  ('ING-DAO-BK', 'dao bk', 'CÁI', 'BÁN HÀNG', 'VD'),
  ('ING-DE-32', 'đế 32', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-DE-35', 'đế 35', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-DE-40', 'đế 40', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-DIA-SET-10', 'dĩa set 10', 'BỘ', 'BÁN HÀNG', 'SG'),
  ('ING-GIAY-LOT-KHAY', 'giấy lót khây', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-HOP-1-BANH', 'hộp 1 bánh', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-HOP-18X18', 'hộp 18x18', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-HOP-2-BANH', 'hộp 2 bánh', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-HOP-22X20', 'hộp 22x20', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-HOP-25X20', 'hộp 25x20', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-HOP-25X25', 'hộp 25x25', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-HOP-28X20', 'hộp 28x20', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-HOP-28X25', 'hộp 28x25', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-HOP-3-BANH', 'hộp 3 bánh', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-HOP-30X20', 'hộp 30x20', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-HOP-30X25', 'hộp 30x25', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-HOP-30X30', 'hộp 30x30', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-HOP-32X20', 'hộp 32x20', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-HOP-35X20', 'hộp 35x20', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-HOP-35X25', 'hộp 35x25', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-HOP-40X20', 'hộp 40x20', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-HOP-BANH-BAO', 'hộp bánh bao', 'CÁI', 'BÁN HÀNG', 'CHO'),
  ('ING-HOP-BENTO-TRONG', 'hộp bento trong', 'CÁI', 'BÁN HÀNG', 'TT'),
  ('ING-HOP-CRAF-CHU-NHAT', 'hộp Craf chữ nhật', 'CÁI', 'BÁN HÀNG', 'TT'),
  ('ING-HOP-H128', 'hộp H128', 'CÁI', 'BÁN HÀNG', 'TT'),
  ('ING-HOP-H19', 'hộp H19', 'CÁI', 'BÁN HÀNG', 'TT'),
  ('ING-HOP-H24', 'hộp H24', 'CÁI', 'BÁN HÀNG', 'VD'),
  ('ING-HOP-P500D', 'hộp P500D', 'CÁI', 'BÁN HÀNG', 'CHO'),
  ('ING-HOP-CRAF-VUONG', 'hộp Craf vuông', 'CÁI', 'BÁN HÀNG', 'TT'),
  ('ING-HOP-HT203', 'hộp HT203', 'CÁI', 'BÁN HÀNG', 'TT'),
  ('ING-HOP-TAM-GIAC', 'hộp tam giác', 'CÁI', 'BÁN HÀNG', 'VD'),
  ('ING-HOP-H03', 'hộp H03', 'CÁI', 'BÁN HÀNG', 'TT'),
  ('ING-NEN-0', 'nến 0', 'CÁI', 'BÁN HÀNG', 'VD'),
  ('ING-NEN-1', 'nến 1', 'CÁI', 'BÁN HÀNG', 'VD'),
  ('ING-NEN-2', 'nến 2', 'CÁI', 'BÁN HÀNG', 'VD'),
  ('ING-NEN-3', 'nến 3', 'CÁI', 'BÁN HÀNG', 'VD'),
  ('ING-NEN-4', 'nến 4', 'CÁI', 'BÁN HÀNG', 'VD'),
  ('ING-NEN-5', 'nến 5', 'CÁI', 'BÁN HÀNG', 'VD'),
  ('ING-NEN-6', 'nến 6', 'CÁI', 'BÁN HÀNG', 'VD'),
  ('ING-NEN-7', 'nến 7', 'CÁI', 'BÁN HÀNG', 'VD'),
  ('ING-NEN-8', 'nến 8', 'CÁI', 'BÁN HÀNG', 'VD'),
  ('ING-NEN-9', 'nến 9', 'CÁI', 'BÁN HÀNG', 'VD'),
  ('ING-NEN-TANG-BANH-KEM', 'nến tặng bánh kem', 'HỘP NHỎ', 'BÁN HÀNG', 'SG'),
  ('ING-NIA', 'nĩa', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-TUI-BANH-KEM-25-28', 'túi bánh kem 25,28', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-TUI-BANH-KEM-30-32', 'túi bánh kem 30,32', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-TUI-BANH-KEM-35-40', 'túi bánh kem 35 ,40', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-TUI-BANH-MI-HOA-CUC', 'túi bánh mì hoa cúc', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-TUI-DONG-BANH-12-X-27', 'túi đóng bánh 12 x 27', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-TUI-DONG-BANH-15-X-22', 'túi đóng bánh 15 x 22', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-TUI-DONG-BANH-17-X-24', 'túi đóng bánh 17 x 24', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-TUI-LAN-TAM-GIAC', 'túi lan tam giác', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-TUI-SANDWICH', 'túi sandwich', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-TUI-SET-QUA', 'túi set quà', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-TUI-SO-1', 'túi số 1', 'KG', 'BÁN HÀNG', 'SG'),
  ('ING-TUI-SO-2', 'túi số 2', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-TUI-SO-3', 'túi số 3', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-TUI-VAI-0018', 'túi vải 0018', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-TUI-VAI-2225', 'túi vải 2225', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-TUI-VAI-2830', 'túi vải 2830', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-TUONG-CA-NHO', 'tương cà nhỏ', 'CÁI', 'BÁN HÀNG', 'CHO'),
  ('ING-HOP-PET-500', 'hộp pet 500', 'CÁI', 'BÁN HÀNG', 'XN'),
  ('ING-HOP-PET-750', 'hộp pet 750', 'CÁI', 'BÁN HÀNG', 'XN'),
  ('ING-TUONG-OT-NHO', 'tương ớt nhỏ', 'CÁI', 'BÁN HÀNG', 'CHO'),
  ('ING-HOP-TIRA-SIZE-10', 'hộp tira size 10', 'CÁI', 'BÁN HÀNG', 'SG'),
  ('ING-BICH-XOP-10', 'bịch xốp 10', 'CÁI', 'BÁN HÀNG', 'CHO'),
  ('ING-TUI-DAN-10', 'túi dán 10', 'CÁI', 'BÁN HÀNG', 'CHO'),
  ('ING-BICH-1-LY', 'bịch 1 ly', 'KG', 'PHA CHẾ', NULL),
  ('ING-BICH-2-LY', 'bịch 2 ly', 'KG', 'PHA CHẾ', NULL),
  ('ING-BOUDO-DUA-LUOI', 'boudo dưa lưới', 'KG', 'PHA CHẾ', NULL),
  ('ING-BOUDO-VAI', 'boudo vải', 'KG', 'PHA CHẾ', NULL),
  ('ING-CAFE', 'cafe', 'BỘ', 'PHA CHẾ', NULL),
  ('ING-DAO-HOP', 'đào hộp', 'HỘP', 'PHA CHẾ', NULL),
  ('ING-LY-LON', 'ly lớn', 'CÁI', 'PHA CHẾ', NULL),
  ('ING-LY-NHO', 'ly nhỏ', 'CÁI', 'PHA CHẾ', NULL),
  ('ING-MAT-ONG', 'mật ong', 'KG', 'PHA CHẾ', NULL),
  ('ING-MUONG-LON', 'muỗng lớn', 'CÁI', 'PHA CHẾ', NULL),
  ('ING-MUONG-NHO', 'muỗng nhỏ', 'CÁI', 'PHA CHẾ', 'TGNL'),
  ('ING-NAP-LY', 'nắp ly', 'CÁI', 'PHA CHẾ', NULL),
  ('ING-NUOC-GAO', 'nước gạo', 'CHAI', 'PHA CHẾ', NULL),
  ('ING-ONG-HUT-LON', 'ống hút lớn', 'CÁI', 'PHA CHẾ', NULL),
  ('ING-ONG-HUT-NHO', 'ống hút nhỏ', 'CÁI', 'PHA CHẾ', NULL),
  ('ING-SIRO-CARAMEN', 'siro caramen', 'KG', 'PHA CHẾ', NULL),
  ('ING-SIRO-DAO', 'siro đào', 'KG', 'PHA CHẾ', NULL),
  ('ING-SIRO-SA', 'siro sả', 'KG', 'PHA CHẾ', NULL),
  ('ING-SIRO-TAO-XANH', 'siro táo xanh', 'KG', 'PHA CHẾ', NULL),
  ('ING-SIRO-VAI', 'siro vải', 'KG', 'PHA CHẾ', NULL),
  ('ING-SIRO-VO-CAM', 'siro vỏ cam', 'KG', 'PHA CHẾ', NULL),
  ('ING-SODA', 'soda', 'CHAI', 'PHA CHẾ', NULL),
  ('ING-SOT-SOCOLA', 'sốt socola', 'KG', 'PHA CHẾ', NULL),
  ('ING-TRA-DEN', 'trà đen', 'KG', 'PHA CHẾ', NULL),
  ('ING-TRA-LAI', 'trà lài', 'KG', 'PHA CHẾ', NULL),
  ('ING-TRA-THAI-XANH', 'trà thái xanh', 'KG', 'PHA CHẾ', NULL),
  ('ING-TRAN-CHAU-DEN', 'trân châu đen', 'KG', 'PHA CHẾ', NULL),
  ('ING-VAI-HOP', 'vải hộp', 'KG', 'PHA CHẾ', NULL),
  ('ING-BANH-OREO', 'bánh oreo', 'CÂY', 'HÀNG SỬ DỤNG CHUNG', 'CHO'),
  ('ING-BERINO-DAU', 'berino dâu', 'KG', 'HÀNG SỬ DỤNG CHUNG', 'XN'),
  ('ING-BERINO-VIET-QUAT', 'berino việt quất', 'KG', 'HÀNG SỬ DỤNG CHUNG', 'TT'),
  ('ING-BO-FE', 'bơ fe', 'KG', 'HÀNG SỬ DỤNG CHUNG', 'VD'),
  ('ING-BOT-BAP', 'bột bắp', 'KG', 'HÀNG SỬ DỤNG CHUNG', 'TT'),
  ('ING-BOT-PHO-MAI', 'bột phô mai', 'KG', 'HÀNG SỬ DỤNG CHUNG', 'TT'),
  ('ING-BOT-SUA', 'bột sữa', 'KG', 'HÀNG SỬ DỤNG CHUNG', 'TGNL'),
  ('ING-BOT-TRA-XANH', 'bột trà xanh', 'KG', 'HÀNG SỬ DỤNG CHUNG', 'TGNL'),
  ('ING-CAFE-DEN-GOI', 'cafe đen gói', 'CÁI', 'HÀNG SỬ DỤNG CHUNG', 'CHO'),
  ('ING-CHA-BONG-CAY', 'chà bông cay', 'KG', 'HÀNG SỬ DỤNG CHUNG', 'SG'),
  ('ING-CHA-BONG-TRANG', 'chà bông trắng', 'KG', 'HÀNG SỬ DỤNG CHUNG', 'SG'),
  ('ING-CHA-BONG-VANG', 'chà bông vàng', 'KG', 'HÀNG SỬ DỤNG CHUNG', 'SG'),
  ('ING-CHEESE', 'cheese', 'KG', 'HÀNG SỬ DỤNG CHUNG', 'SON'),
  ('ING-GALENTINE-LA', 'galentine lá', 'KG', 'HÀNG SỬ DỤNG CHUNG', 'XN'),
  ('ING-HANH-NHAN-LAT', 'hạnh nhân lát', 'KG', 'HÀNG SỬ DỤNG CHUNG', 'TT'),
  ('ING-HOP-BANH-FLAN', 'hộp bánh flan', 'CÁI', 'HÀNG SỬ DỤNG CHUNG', 'TGNL'),
  ('ING-HOP-PANACOTTA', 'hộp panacotta', 'KG', 'HÀNG SỬ DỤNG CHUNG', 'TT'),
  ('ING-KEM-BAZE', 'kem baze', 'KG', 'HÀNG SỬ DỤNG CHUNG', 'SON'),
  ('ING-KEM-GOLD', 'kem gold', 'KG', 'HÀNG SỬ DỤNG CHUNG', 'SON'),
  ('ING-KEM-RICH-LUN', 'kem rich lùn', 'KG', 'HÀNG SỬ DỤNG CHUNG', 'SON'),
  ('ING-KEM-VALUE-VANG', 'kem value vàng', 'KG', 'HÀNG SỬ DỤNG CHUNG', 'SON'),
  ('ING-MAU-DEN', 'màu đen', 'KG', 'HÀNG SỬ DỤNG CHUNG', 'SG'),
  ('ING-MAU-SIEU-DO', 'màu siêu đỏ', 'KG', 'HÀNG SỬ DỤNG CHUNG', 'SG'),
  ('ING-MAU-VANG-TUOI', 'màu vàng tươi', 'KG', 'HÀNG SỬ DỤNG CHUNG', 'SG'),
  ('ING-PHO-MAI-LAT', 'pho mai lát', 'KG', 'HÀNG SỬ DỤNG CHUNG', 'CHO'),
  ('ING-PHOMAI-BO-CUOI', 'phomai bò cười', 'KG', 'HÀNG SỬ DỤNG CHUNG', 'CHO'),
  ('ING-SOCOLA-DEN', 'socola đen', 'KG', 'HÀNG SỬ DỤNG CHUNG', 'XN'),
  ('ING-SOCOLA-SET', 'socola sệt', 'KG', 'HÀNG SỬ DỤNG CHUNG', 'VD'),
  ('ING-SOCOLA-TRANG', 'socola trắng', 'KG', 'HÀNG SỬ DỤNG CHUNG', 'XN'),
  ('ING-SUA-CHUA-KHONG-DUONG', 'sữa chua không đường', 'HỘP', 'HÀNG SỬ DỤNG CHUNG', 'CHO'),
  ('ING-SUA-DAC', 'sữa đặc', 'KG', 'HÀNG SỬ DỤNG CHUNG', 'CHO'),
  ('ING-SUA-TUOI', 'sữa tươi', 'KG', 'HÀNG SỬ DỤNG CHUNG', 'TGNL'),
  ('ING-THOM-SEN', 'thơm sên', 'KG', 'HÀNG SỬ DỤNG CHUNG', 'CHO'),
  ('ING-TRUNG-MUOI', 'trứng muối', 'QUẢ', 'HÀNG SỬ DỤNG CHUNG', 'TT'),
  ('ING-BAP-MY', 'bắp mỹ', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-CA-ROT', 'cà rốt', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-CAM', 'cam', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-CHA', 'chả', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-CHANH', 'chanh', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-CHANH-DAY-TRAI', 'chanh dây trái', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-CHUOI', 'chuối', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-CU-SAN', 'củ sắn', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-DA-BAO', 'da bao', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-DAU-HA-LAN', 'đậu hà lan', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-DAU-PHONG', 'đậu phộng', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-HANH-LA-2', 'hành lá', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-HANH-PHI', 'hành phi', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-HANH-TAY-2', 'hành tây', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-HANH-TIM', 'hành tím', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-KHOAI-LANG', 'khoai lang', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-LA-BAC-HA', 'lá bạc hà', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-LA-DUA', 'lá dứa', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-LAP-XUONG', 'lạp xưởng', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-ME-DEN', 'mè đen', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-ME-TRANG', 'mè trắng', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-MO-HEO', 'mỡ heo', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-MUC-2', 'mực', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-MUT-BI', 'mứt bí', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-NAM-MEO', 'nấm mèo', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-NGO-RI', 'ngò rí', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-OT-CHUONG-2', 'ớt chuông', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-SA', 'sả', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-TAT', 'tắt', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-THANH-CUA', 'thanh cua', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-THIT-XAY', 'thịt xay', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-THOM-TRAI', 'thơm trái', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-TOI', 'tỏi', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-TOM-2', 'tôm', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-TRUNG-CUT', 'trứng cút', 'QUẢ', 'HÀNG CHỢ', NULL),
  ('ING-TRUNG-VIT', 'trứng vịt', 'QUẢ', 'HÀNG CHỢ', NULL),
  ('ING-XI-MUOI', 'xí muội', 'KG', 'HÀNG CHỢ', NULL),
  ('ING-BANG-KEO-LON', 'băng keo lớn', 'CÁI', 'HÀNG CHỢ', 'CHO'),
  ('ING-BANG-KEO-MINI', 'băng keo mini', 'CÁI', 'HÀNG CHỢ', 'CHO'),
  ('ING-BANG-KEO-MY-LY', 'băng keo mỹ lý', 'CÁI', 'HÀNG CHỢ', 'SG'),
  ('ING-BANG-KEO-SW', 'băng keo sw', 'CÁI', 'HÀNG CHỢ', 'CHO'),
  ('ING-BAO-TAM-GIAC', 'bao tam giác', 'KG', 'HÀNG CHỢ', 'VD'),
  ('ING-BAO-TAY-Y-TE', 'bao tay y tế', 'HỘP', 'HÀNG CHỢ', 'CHO'),
  ('ING-BICH-PD-TU-BANH-BAO', 'bịch pd (tủ bánh bao)', 'KG', 'HÀNG CHỢ', 'CHO'),
  ('ING-BOT-GIAT', 'bột giặt', 'KG', 'HÀNG CHỢ', 'CHO'),
  ('ING-CAY-DANH-BOT', 'cây đánh bột', 'CÁI', 'HÀNG CHỢ', 'CHO'),
  ('ING-CAY-LAU-SAN', 'cây lau sàn', 'CÁI', 'HÀNG CHỢ', 'CHO'),
  ('ING-CAY-VET-BOT', 'cây vét bột', 'CÁI', 'HÀNG CHỢ', 'CHO'),
  ('ING-CHOI', 'chổi', 'CÁI', 'HÀNG CHỢ', 'CHO'),
  ('ING-CO-QUET', 'cọ quét', 'CÁI', 'HÀNG CHỢ', 'CHO'),
  ('ING-DAY-COT-BANH', 'dây cột bánh', 'CÁI', 'HÀNG CHỢ', 'CHO'),
  ('ING-DUNG-CU-HOT-RAC', 'dụng cụ hốt rác', 'CÁI', 'HÀNG CHỢ', 'CHO'),
  ('ING-GHIM-BAM', 'ghim bấm', 'CÁI', 'HÀNG CHỢ', 'CHO'),
  ('ING-GIAY-LAN', 'giấy lan', 'KG', 'HÀNG CHỢ', 'CHO'),
  ('ING-KHAN-GIAY', 'khăn giấy', 'CÂY', 'HÀNG CHỢ', 'CHO'),
  ('ING-MANG-BOC-THUC-PHAM', 'màng bọc thực phẩm', 'CÂY', 'HÀNG CHỢ', 'CHO'),
  ('ING-MIENG-LAU-SAN', 'miếng lau sàn', 'CÁI', 'HÀNG CHỢ', 'CHO'),
  ('ING-NUOC-LAU-KINH', 'nước lau kính', 'CÁI', 'HÀNG CHỢ', 'CHO'),
  ('ING-NUOC-LAU-SAN', 'nước lau sàn', 'KG', 'HÀNG CHỢ', 'CHO'),
  ('ING-NUOC-RUA-CHEN', 'nước rửa chén', 'KG', 'HÀNG CHỢ', 'CHO'),
  ('ING-NUOC-XIT-TAY-LO', 'nước xịt tẩy lò', 'CÁI', 'HÀNG CHỢ', 'CHO'),
  ('ING-PIN-TIEU', 'pin tiểu', 'CÁI', 'HÀNG CHỢ', 'CHO'),
  ('ING-TAM-TRE', 'tăm tre', 'CÁI', 'HÀNG CHỢ', 'CHO'),
  ('ING-THUN', 'thun', 'KG', 'HÀNG CHỢ', 'CHO'),
  ('ING-THUOC-TAY-CHA-SAN', 'thuốc tẩy chà sân', 'CÁI', 'HÀNG CHỢ', 'CHO'),
  ('ING-TUI-DUNG-RAC', 'túi đựng rác', 'CÁI', 'HÀNG CHỢ', 'CHO'),
  ('ING-TUI-ZIP-0-5KG', 'túi zip 0.5kg', 'KG', 'HÀNG CHỢ', 'CHO'),
  ('ING-TUI-ZIP-1KG', 'túi zip 1kg', 'KG', 'HÀNG CHỢ', 'CHO'),
  ('ING-VI-CHA-NOI', 'vỉ chà nồi', 'CÁI', 'HÀNG CHỢ', 'CHO'),
  ('ING-VIEM', 'viêm', 'CÁI', 'HÀNG CHỢ', 'CHO'),
  ('ING-XIEN-QUE', 'xiên que', 'BỘ', 'HÀNG CHỢ', 'CHO'),
  ('ING-XIEN-QUE-DONUT', 'xiên que donut', 'BỘ', 'HÀNG CHỢ', 'SG'),
  ('ING-BAO-TAY-LEN-CAP', 'bao tay len ( cặp)', 'CÁI', 'HÀNG CHỢ', 'CHO'),
  ('ING-GIAY-BAO', 'giấy báo', 'KG', 'HÀNG CHỢ', 'CHO'),
  ('ING-BAO-TAY-LO', 'bao tay lò', 'CÁI', 'HÀNG CHỢ', 'SG'),
  ('ING-GIAY-SILICON', 'giấy silicon', 'KG', 'HÀNG CHỢ', 'SG'),
  ('ING-BICH-BAT-SUKEM', 'bịch bắt sukem', 'KG', 'HÀNG CHỢ', 'SG'),
  ('ING-DAU-BAT-SUKEM', 'đầu bắt sukem', 'KG', 'HÀNG CHỢ', 'SG')
) AS v(code, name, unit, category, supplier_code)
LEFT JOIN supplier s ON s.code = v.supplier_code
ON CONFLICT (code) DO NOTHING;

-- 4) ingredient_price (lịch sử giá tham khảo; 130/345 dòng có GIÁ, effective_date = ngày import 2026-07-09)
-- lot_ref để NULL vì đây là giá tham khảo ban đầu, không gắn với lô nhập cụ thể nào
INSERT INTO ingredient_price (item_id, supplier_id, price, effective_date, lot_ref)
SELECT i.id, s.id, v.price, '2026-07-09', NULL
FROM (VALUES
  ('ING-BO-ANCHOR', 'TGNL', 280000),
  ('ING-BO-NAUY', 'VD', 161000),
  ('ING-BO-THE', 'TT', 119000),
  ('ING-BO-THOM', 'VD', 81770),
  ('ING-BO-TUONG-AN', 'VD', 48750),
  ('ING-BOT-555', 'VD', 17760),
  ('ING-BOT-BEO', 'TT', 38000),
  ('ING-BOT-BH-25KG', 'TT', 18600),
  ('ING-BOT-BH-XANH', 'TT', 28000),
  ('ING-BOT-BUTTER-MILK', 'VD', 310000),
  ('ING-BOT-CACAO', 'TT', 87000),
  ('ING-BOT-KHOAI-LANG-TIM', 'XN', 70000),
  ('ING-BOT-NANG', 'TT', 31000),
  ('ING-BOT-NOI', 'VD', 62000),
  ('ING-BOT-REDVELET', 'VD', 100000),
  ('ING-BOT-TARTA', 'VD', 260000),
  ('ING-BOT-XE-DAP', 'VD', 15100),
  ('ING-CHEN-GIAY-SO-15', 'TT', 50000),
  ('ING-CHEN-GIAY-SO-8', 'TT', 42000),
  ('ING-DUONG-BOT', 'VD', 45000),
  ('ING-DUONG-CAT', 'CHO', 20000),
  ('ING-HOP-THIEC-CHU-NHAT', 'TT', 1650),
  ('ING-HOP-LAN-CHUOI', 'SG', 1900),
  ('ING-HUONG-DUA', 'VD', 123000),
  ('ING-HUONG-SUA', 'VD', 170000),
  ('ING-KEM-PHO-MAI', 'SON', 113000),
  ('ING-KEM-VIVO', 'VD', 79000),
  ('ING-MEN-LAT', 'VD', 116000),
  ('ING-MEN-NGOT', 'VD', 116000),
  ('ING-MUT-CAM-NHA-DAM', 'TGNL', 92000),
  ('ING-NHAN-DAU-XANH', 'VD', 69000),
  ('ING-NHAN-MON', 'VD', 75000),
  ('ING-NHO', 'TT', 90000),
  ('ING-PHOMAI-SOI', 'TGNL', 173000),
  ('ING-PHU-GIA-LAT', 'VD', 80000),
  ('ING-PHU-GIA-NGOT', 'VD', 98000),
  ('ING-SP-5KG', 'VD', 71000),
  ('ING-SU-KEM-1-KG', 'VD', 114000),
  ('ING-BOT-TRA-XANH-COSY', 'TGNL', 750000),
  ('ING-GALENTINE-BOT', 'TT', 300000),
  ('ING-GIAY-LOT-PENTO', 'SG', 31),
  ('ING-GODEN-FARM-CHANH-DAY', 'XN', 100000),
  ('ING-GODEN-FARM-KIWI', 'XN', 100000),
  ('ING-HOP-A93', 'XN', 1100),
  ('ING-HOP-H15-BAU', 'TT', 850),
  ('ING-HOP-PENTO', 'TT', 1700),
  ('ING-HUONG-BAP', 'VD', 300000),
  ('ING-KEM-MAN', 'SON', 88000),
  ('ING-KEM-NIGARI-FARM', 'SON', 87000),
  ('ING-MASCAPON', 'XN', 255000),
  ('ING-MAU-CAM-TUOI', 'SG', 43200),
  ('ING-MAU-DA-IVORY', 'SG', 43200),
  ('ING-MAU-DO-CHERRY', 'SG', 43200),
  ('ING-MAU-HONG-DAU', 'SG', 43200),
  ('ING-MAU-NAU-GO', 'SG', 43200),
  ('ING-MAU-TIM-LAVENDER', 'SG', 43200),
  ('ING-MAU-TIM-RASPERRY', 'SG', 43200),
  ('ING-MAU-VANG-DAT', 'SG', 43200),
  ('ING-MAU-XANH-DA-TROI', 'SG', 43200),
  ('ING-MAU-XANH-REU', 'SG', 43200),
  ('ING-MAU-XANH-TRAI-BO', 'SG', 43200),
  ('ING-MY-CREAMS', 'SON', 69000),
  ('ING-RUOU-KLUA', 'TT', 380000),
  ('ING-SOCOLA-NUT-DEN', 'XN', 350000),
  ('ING-WHIPPING', 'TGNL', 146000),
  ('ING-YUM-CHERRY', 'SG', 124200),
  ('ING-YUM-DAU', 'SG', 124200),
  ('ING-DAO-BK', 'VD', 640),
  ('ING-DIA-SET-10', 'SG', 3200),
  ('ING-GIAY-LOT-KHAY', 'SG', 473),
  ('ING-HOP-BENTO-TRONG', 'TT', 1800),
  ('ING-HOP-CRAF-CHU-NHAT', 'TT', 1700),
  ('ING-HOP-H128', 'TT', 650),
  ('ING-HOP-H19', 'TT', 1200),
  ('ING-HOP-CRAF-VUONG', 'TT', 1700),
  ('ING-HOP-TAM-GIAC', 'VD', 1000),
  ('ING-HOP-H03', 'TT', 800),
  ('ING-NEN-0', 'VD', 14500),
  ('ING-NEN-1', 'VD', 14500),
  ('ING-NEN-2', 'VD', 14500),
  ('ING-NEN-3', 'VD', 14500),
  ('ING-NEN-4', 'VD', 14500),
  ('ING-NEN-5', 'VD', 14500),
  ('ING-NEN-6', 'VD', 14500),
  ('ING-NEN-7', 'VD', 14500),
  ('ING-NEN-8', 'VD', 14500),
  ('ING-NEN-9', 'VD', 14500),
  ('ING-NEN-TANG-BANH-KEM', 'SG', 1800),
  ('ING-NIA', 'SG', 140),
  ('ING-TUI-BANH-MI-HOA-CUC', 'SG', 130000),
  ('ING-TUI-DONG-BANH-12-X-27', 'SG', 360),
  ('ING-TUI-DONG-BANH-15-X-22', 'SG', 165000),
  ('ING-TUI-DONG-BANH-17-X-24', 'SG', 165000),
  ('ING-TUI-LAN-TAM-GIAC', 'SG', 167000),
  ('ING-TUI-SANDWICH', 'SG', 148000),
  ('ING-TUI-SO-1', 'SG', 70000),
  ('ING-TUI-SO-2', 'SG', 68000),
  ('ING-TUI-SO-3', 'SG', 63000),
  ('ING-TUI-VAI-0018', 'SG', 6000),
  ('ING-TUI-VAI-2225', 'SG', 7000),
  ('ING-TUI-VAI-2830', 'SG', 7500),
  ('ING-HOP-PET-500', 'XN', 6800),
  ('ING-HOP-PET-750', 'XN', 8200),
  ('ING-MUONG-NHO', 'TGNL', 280000),
  ('ING-BERINO-DAU', 'XN', 96000),
  ('ING-BERINO-VIET-QUAT', 'TT', 110000),
  ('ING-BO-FE', 'VD', 101000),
  ('ING-BOT-BAP', 'TT', 28000),
  ('ING-BOT-TRA-XANH', 'TGNL', 750000),
  ('ING-CHA-BONG-CAY', 'SG', 155000),
  ('ING-CHA-BONG-TRANG', 'SG', 145000),
  ('ING-CHA-BONG-VANG', 'SG', 145000),
  ('ING-CHEESE', 'SON', 195000),
  ('ING-GALENTINE-LA', 'XN', 680000),
  ('ING-HANH-NHAN-LAT', 'TT', 270000),
  ('ING-HOP-BANH-FLAN', 'TGNL', 340000),
  ('ING-HOP-PANACOTTA', 'TT', 320),
  ('ING-KEM-BAZE', 'SON', 82000),
  ('ING-KEM-GOLD', 'SON', 68000),
  ('ING-KEM-RICH-LUN', 'SON', 31000),
  ('ING-KEM-VALUE-VANG', 'SON', 59000),
  ('ING-MAU-DEN', 'SG', 43200),
  ('ING-MAU-SIEU-DO', 'SG', 43200),
  ('ING-MAU-VANG-TUOI', 'SG', 43200),
  ('ING-SOCOLA-DEN', 'XN', 124000),
  ('ING-SOCOLA-SET', 'VD', 145250),
  ('ING-SOCOLA-TRANG', 'XN', 116000),
  ('ING-SUA-TUOI', 'TGNL', 29000),
  ('ING-TRUNG-MUOI', 'TT', 4100),
  ('ING-BAO-TAM-GIAC', 'VD', 83000)
) AS v(code, supplier_code, price)
JOIN item i ON i.code = v.code
LEFT JOIN supplier s ON s.code = v.supplier_code;